### ISSUE TITLE
Can't convert ONNX to Tensorflow

### ISSUE THREAD

**Issue by BrunoVox** [onnx/onnx-tensorflow#1017]
**Describe the bug**

I have trained a custom FasterRCNN model using PyTorch ([docs](https://pytorch.org/vision/stable/generated/torchvision.models.detection.fasterrcnn_mobilenet_v3_large_320_fpn.html#torchvision.models.detection.fasterrcnn_mobilenet_v3_large_320_fpn)) and converted it to ONNX. Up to here everything ran ok. Converting from ONNX to Tensorflow is the real issue here. Whenever I try converting it, the following ValueError is shown:

```
Traceback (most recent call last):
  File "/home/b-a-oliveira/anaconda3/envs/detection/bin/onnx-tf", line 8, in <module>
    sys.exit(main())
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/onnx_tf/cli.py", line 20, in main
    return onnx_tf.converter.main(args[1:])
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/onnx_tf/converter.py", line 21, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/onnx_tf/converter.py", line 147, in convert
    tf_rep.export_graph(outdir)
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/onnx_tf/backend_rep.py", line 143, in export_graph
    signatures=self.tf_module.__call__.get_concrete_function(
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1264, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1244, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 785, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2983, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3292, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3130, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1161, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 677, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3831, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/onnx_tf/backend_tf_module.py", line 99, in __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/onnx_tf/backend.py", line 347, in _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/onnx_tf/handlers/handler.py", line 58, in handle  *
        cls.args_check(node, **kwargs)
    File "/home/b-a-oliveira/anaconda3/envs/detection/lib/python3.8/site-packages/onnx_tf/handlers/backend/split.py", line 18, in args_check  *
        x_rank =  len(kwargs["tensor_dict"][node.inputs[0]].get_shape().as_list())

    ValueError: as_list() is not defined on an unknown TensorShape.
```

I'm not sure how to enable this conversion, because I don't know what this error means.

**To Reproduce**

Run the following Notebook on Colab:

[Notebook](https://colab.research.google.com/drive/1VqyksFsonwuAYA84GVPz48u5Di0rN55i?usp=sharing)

But first, download the ONNX model file in the next section.

**ONNX model file**

[ONNX model](https://drive.google.com/file/d/1VQTkpkjrauvVhB0a35hL1aEXkgsdnNgO/view?usp=sharing)

**Python, ONNX, ONNX-TF, Tensorflow version**

 - Python version: 3.8.12
 - ONNX version: 1.11.0
 - ONNX-TF version: 1.10.0
 - Tensorflow version: 2.8.0

**Comment by chinhuang007** [comment]
In the ONNX model, the input to a split operator has unknown rank, which caused the validation to fail. We don't generally handle inputs with unknown ranks. However for this particular case, I created a small patch to allow the conversion to continue. Please note the conversion might take a long time since the model is pretty big.

**Comment by Egbert77** [comment]
> In the ONNX model, the input to a split operator has unknown rank, which caused the validation to fail. We don't generally handle inputs with unknown ranks. However for this particular case, I created a small patch to allow the conversion to continue. Please note the conversion might take a long time since the model is pretty big.

Is this error due to the same reason, I have not found a suitable solution so far

`2022-09-29 03:42:02.198948: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-29 03:42:04.131663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10417 MB memory:  -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1
2022-09-29 03:42:04.133176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 10417 MB memory:  -> device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:82:00.0, compute capability: 6.1
2022-09-29 03:42:14,773 - onnx-tf - WARNING - Using the pooling op in compatibility mode. This means your graph cannot be serialized.
2022-09-29 03:42:15,928 - onnx-tf - WARNING - Using the pooling op in compatibility mode. This means your graph cannot be serialized.
Traceback (most recent call last):
  File "onnx2tf.py", line 22, in <module>
    tf_rep.export_graph(TF_PATH)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/backend_rep.py", line 144, in export_graph
    **self.signatures))
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1264, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1244, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 786, in _initialize
    *args, **kwds))
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2983, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3292, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3140, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1161, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 677, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3831, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/backend_tf_module.py", line 99, in __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/backend.py", line 347, in _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/handlers/handler.py", line 59, in handle  *
        return ver_handle(node, **kwargs)
    File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/handlers/backend/conv.py", line 15, in version_11  *
        return cls.conv(node, kwargs["tensor_dict"])
    File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/handlers/backend/conv_mixin.py", line 30, in conv  *
        x_rank = len(x.get_shape())

    ValueError: Cannot take the length of shape with unknown rank.`

**Comment by Egbert77** [comment]
> In the ONNX model, the input to a split operator has unknown rank, which caused the validation to fail. We don't generally handle inputs with unknown ranks. However for this particular case, I created a small patch to allow the conversion to continue. Please note the conversion might take a long time since the model is pretty big.

Is this error due to the same reason?, I have not found a suitable solution so far

`2022-09-29 03:42:02.198948: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-29 03:42:04.131663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10417 MB memory: -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1
2022-09-29 03:42:04.133176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 10417 MB memory: -> device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:82:00.0, compute capability: 6.1
2022-09-29 03:42:14,773 - onnx-tf - WARNING - Using the pooling op in compatibility mode. This means your graph cannot be serialized.
2022-09-29 03:42:15,928 - onnx-tf - WARNING - Using the pooling op in compatibility mode. This means your graph cannot be serialized.
Traceback (most recent call last):
File "onnx2tf.py", line 22, in
tf_rep.export_graph(TF_PATH)
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/backend_rep.py", line 144, in export_graph
**self.signatures))
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1264, in get_concrete_function
concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1244, in _get_concrete_function_garbage_collected
self._initialize(args, kwargs, add_initializers_to=initializers)
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 786, in _initialize
*args, **kwds))
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2983, in _get_concrete_function_internal_garbage_collected
graph_function, _ = self._maybe_define_function(args, kwargs)
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3292, in _maybe_define_function
graph_function = self._create_graph_function(args, kwargs)
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3140, in _create_graph_function
capture_by_value=self._capture_by_value),
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1161, in func_graph_from_py_func
func_outputs = python_func(*func_args, **func_kwargs)
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 677, in wrapped_fn
out = weak_wrapped_fn().wrapped(*args, **kwds)
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3831, in bound_method_wrapper
return wrapped_fn(*args, **kwargs)
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1147, in autograph_handler
raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/backend_tf_module.py", line 99, in __call__  *
    output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/backend.py", line 347, in _onnx_node_to_tensorflow_op  *
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/handlers/handler.py", line 59, in handle  *
    return ver_handle(node, **kwargs)
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/handlers/backend/conv.py", line 15, in version_11  *
    return cls.conv(node, kwargs["tensor_dict"])
File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/handlers/backend/conv_mixin.py", line 30, in conv  *
    x_rank = len(x.get_shape())
ValueError: Cannot take the length of shape with unknown rank.`

**Comment by Egbert77** [comment]
> In the ONNX model, the input to a split operator has unknown rank, which caused the validation to fail. We don't generally handle inputs with unknown ranks. However for this particular case, I created a small patch to allow the conversion to continue. Please note the conversion might take a long time since the model is pretty big.

Is this error due to the same reason? I have not found a suitable solution so far, 
```
2022-09-29 03:42:02.198948: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-29 03:42:04.131663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10417 MB memory:  -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1
2022-09-29 03:42:04.133176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 10417 MB memory:  -> device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:82:00.0, compute capability: 6.1
2022-09-29 03:42:14,773 - onnx-tf - WARNING - Using the pooling op in compatibility mode. This means your graph cannot be serialized.
2022-09-29 03:42:15,928 - onnx-tf - WARNING - Using the pooling op in compatibility mode. This means your graph cannot be serialized.
Traceback (most recent call last):
  File "onnx2tf.py", line 22, in <module>
    tf_rep.export_graph(TF_PATH)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/backend_rep.py", line 144, in export_graph
    **self.signatures))
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1264, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1244, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 786, in _initialize
    *args, **kwds))
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2983, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3292, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3140, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1161, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 677, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3831, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/backend_tf_module.py", line 99, in __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/backend.py", line 347, in _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/handlers/handler.py", line 59, in handle  *
        return ver_handle(node, **kwargs)
    File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/handlers/backend/conv.py", line 15, in version_11  *
        return cls.conv(node, kwargs["tensor_dict"])
    File "/root/anaconda3/envs/onnx2tf/lib/python3.7/site-packages/onnx_tf/handlers/backend/conv_mixin.py", line 30, in conv  *
        x_rank = len(x.get_shape())

    ValueError: Cannot take the length of shape with unknown rank.
```
