### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_probability'

### ISSUE THREAD

**Issue by langhuihui** [onnx/onnx-tensorflow#1072]
```
/Users/dexter/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/dexter/Library/Python/3.9/bin/onnx-tf", line 5, in <module>
    from onnx_tf.cli import main
  File "/Users/dexter/Library/Python/3.9/lib/python/site-packages/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/Users/dexter/Library/Python/3.9/lib/python/site-packages/onnx_tf/backend.py", line 28, in <module>
    from onnx_tf.common.handler_helper import get_all_backend_handlers
  File "/Users/dexter/Library/Python/3.9/lib/python/site-packages/onnx_tf/common/handler_helper.py", line 3, in <module>
    from onnx_tf.handlers.backend import *  # noqa
  File "/Users/dexter/Library/Python/3.9/lib/python/site-packages/onnx_tf/handlers/backend/bernoulli.py", line 2, in <module>
    from tensorflow_probability import distributions as tfd
ModuleNotFoundError: No module named 'tensorflow_probability'
```

**Comment by devhoodit** [comment]
try
pip install tensorflow-probability==0.23.0
if tf version is 2.15.0
