### ISSUE TITLE
KeyError: 'shape'

### ISSUE THREAD

**Issue by tom888888** [onnx/onnx-tensorflow#161]
I use this example from
https://github.com/onnx/tutorials/blob/master/tutorials/PytorchCaffe2SuperResolution.ipynb
to export  super_resolution.onnx
and run in Tensorflow ,this error occurs
I did run programming with GPU on jupyter noebook
## Error message
```
KeyErrorTraceback (most recent call last)
<ipython-input-4-ccb916f2b693> in <module>()
      2 from onnx_tf.backend import prepare
      3 model = onnx.load('super_resolution.onnx')
----> 4 tf_rep = prepare(model)

/usr/local/lib/python3.6/dist-packages/onnx_tf/backend.py in prepare(cls, model, device, **kwargs)
    386 
    387     original_input_dict, predict_net = (
--> 388         cls.onnx_graph_to_tensorflow_net(model.graph))
    389 
    390     initialized = {init.name for init in model.graph.initializer}

/usr/local/lib/python3.6/dist-packages/onnx_tf/backend.py in onnx_graph_to_tensorflow_net(cls, graph_def)
    370       node = OnnxNode(node)
    371 
--> 372       output_ops = cls._onnx_node_to_tensorflow_op(node, input_dict)
    373       curr_node_output_map = list(zip(node.outputs, output_ops))
    374       input_dict = dict(list(input_dict.items()) +

/usr/local/lib/python3.6/dist-packages/onnx_tf/backend.py in _onnx_node_to_tensorflow_op(cls, node, input_dict)
    422     if handler_name in dir(cls):
    423       method_to_call = getattr(cls, handler_name)
--> 424       return method_to_call(node, input_dict)
    425     else:
    426       raise NotImplementedError("{} op is not implemented.".format(node.op_type))

/usr/local/lib/python3.6/dist-packages/onnx_tf/backend.py in handle_reshape(cls, node, input_dict)
    919   def handle_reshape(cls, node, input_dict):
    920     tensor = input_dict[node.inputs[0]]
--> 921     shape = tf.constant(node.attrs["shape"])
    922     return [tf.reshape(tensor, shape)]
    923 

KeyError: 'shape'
```
## this is my code:
```
import io
import numpy as np

from torch import nn
from torch.autograd import Variable
import torch.utils.model_zoo as model_zoo
import torch.onnx

import torch.nn as nn
import torch.nn.init as init


class SuperResolutionNet(nn.Module):
    def __init__(self, upscale_factor, inplace=False):
        super(SuperResolutionNet, self).__init__()

        self.relu = nn.ReLU(inplace=inplace)
        self.conv1 = nn.Conv2d(1, 64, (5, 5), (1, 1), (2, 2))
        self.conv2 = nn.Conv2d(64, 64, (3, 3), (1, 1), (1, 1))
        self.conv3 = nn.Conv2d(64, 32, (3, 3), (1, 1), (1, 1))
        self.conv4 = nn.Conv2d(32, upscale_factor ** 2, (3, 3), (1, 1), (1, 1))
        self.pixel_shuffle = nn.PixelShuffle(upscale_factor)

        self._initialize_weights()

    def forward(self, x):
        x = self.relu(self.conv1(x))
        x = self.relu(self.conv2(x))
        x = self.relu(self.conv3(x))
        x = self.pixel_shuffle(self.conv4(x))
        return x

    def _initialize_weights(self):
        init.orthogonal(self.conv1.weight, init.calculate_gain('relu'))
        init.orthogonal(self.conv2.weight, init.calculate_gain('relu'))
        init.orthogonal(self.conv3.weight, init.calculate_gain('relu'))
        init.orthogonal(self.conv4.weight)

torch_model = SuperResolutionNet(upscale_factor=3)

model_url = 'https://s3.amazonaws.com/pytorch/test_data/export/superres_epoch100-44c6958e.pth'
batch_size = 1
torch_model.load_state_dict(model_zoo.load_url(model_url))
torch_model.train(False)
x = Variable(torch.randn(batch_size, 1, 224, 224), requires_grad=True)

torch_out = torch.onnx._export(torch_model, x ,  "super_resolution.onnx",  export_params=True)   

import onnx
from onnx_tf.backend import prepare
model = onnx.load('super_resolution.onnx')
tf_rep = prepare(model)
```
## my Python Environment
python 3.6.3
apt-get install protobuf-compiler libprotoc-dev
pip install git+https://github.com/onnx/onnx-tensorflow.git@master
pip install git+https://github.com/onnx/onnx.git@master

Could you please advice how to solve out this error
Thank you

**Comment by fumihwh** [comment]
@tom888888 
`handle_reshape` has no long been in `backend.py`.
At least it has been moved to `backend_v1.py` and `backend_v5.py`.
If you don't has them, could you check your installation of onnx-tf?

**Comment by tom888888** [comment]
thank you for your reply
how could i check my installation of onnx-tf?
or i should do `pip install onnx-tf`

**Comment by tom888888** [comment]
and i try to run programming with CPU in docker container ,this error occurs
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/onnx-tensorflow/onnx_tf/backend.py", line 342, in prepare
    super(TensorflowBackendBase, cls).prepare(model, device, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/onnx/backend/base.py", line 53, in prepare
    onnx.checker.check_model(model)
  File "/opt/conda/lib/python3.6/site-packages/onnx/checker.py", line 77, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1].

==> Context: Bad node spec: input: "15" input: "16" output: "17" op_type: "Reshape" doc_string: "/opt/conda/lib/python3.
6/site-packages/torch/nn/functional.py(1660): pixel_shuffle\n/opt/conda/lib/python3.6/site-packages/torch/nn/modules/pix
elshuffle.py(40): forward\n/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(479): _slow_forward\n/opt/c
onda/lib/python3.6/site-packages/torch/nn/modules/module.py(489): __call__\n<ipython-input-2-ee3d136ed8b1>(22): forward\
n/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(479): _slow_forward\n/opt/conda/lib/python3.6/site-pa
ckages/torch/nn/modules/module.py(489): __call__\n/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py(288): for
ward\n/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(491): __call__\n/opt/conda/lib/python3.6/site-pa
ckages/torch/jit/__init__.py(255): get_trace_graph\n/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py(134): _ex
port\n/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py(20): _export\n<ipython-input-5-4144cbb80df0>(8): <mo
dule>\n/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2910): run_code\n/opt/conda/lib/python3.6
/site-packages/IPython/core/interactiveshell.py(2850): run_ast_nodes\n/opt/conda/lib/python3.6/site-packages/IPython/cor
e/interactiveshell.py(2728): run_cell\n/opt/conda/lib/python3.6/site-packages/ipykernel/zmqshell.py(537): run_cell\n/opt
/conda/lib/python3.6/site-packages/ipykernel/ipkernel.py(208): do_execute\n/opt/conda/lib/python3.6/site-packages/ipyker
nel/kernelbase.py(399): execute_request\n/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py(233): dispatch_s
hell\n/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py(283): dispatcher\n/opt/conda/lib/python3.6/site-pac
kages/tornado/stack_context.py(277): null_wrapper\n/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py(414
): _run_callback\n/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py(472): _handle_recv\n/opt/conda/lib/p
ython3.6/site-packages/zmq/eventloop/zmqstream.py(440): _handle_events\n/opt/conda/lib/python3.6/site-packages/tornado/s
tack_context.py(277): null_wrapper\n/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py(888): start\n/opt/conda/lib
/python3.6/site-packages/zmq/eventloop/ioloop.py(177): start\n/opt/conda/lib/python3.6/site-packages/ipykernel/kernelapp
.py(478): start\n/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py(658): launch_instance\n/opt/cond
a/lib/python3.6/site-packages/ipykernel_launcher.py(16): <module>\n/opt/conda/lib/python3.6/runpy.py(85): _run_code\n/op
t/conda/lib/python3.6/runpy.py(193): _run_module_as_main\n"
```
## my Python Environment
python 3.6.4
apt-get install protobuf-compiler libprotoc-dev
pip install onnx-tf
pip install git+https://github.com/onnx/onnx.git@master
pip install tensorflow

Could you please advice how to solve out this error
Thank you

**Comment by fumihwh** [comment]
@tom888888 
Could you clone onnx-tensorflow to local and install by `pip install -e .`?
Second, onnx in your docker is outdated.

**Comment by tom888888** [comment]
I did the same thing in docker as i did in jupyter.
why docker occur error?
Could you please advice how to solve out this error
Thank you

**Comment by fumihwh** [comment]
I am not familiar with docker.
But https://docs.docker.com/engine/reference/commandline/commit/ will help.

**Comment by tom888888** [comment]
@fumihwh 
thank you so much ,problem solved out
I continue to try docker
