### ISSUE TITLE
How to convert a tensorflow model with multi ouput nodes to onnx format

### ISSUE THREAD

**Issue by fengshikun** [onnx/onnx-tensorflow#203]
I learn from such code to convert a tensorflow model to onnx format
```
import tensorflow as tf
from onnx_tf.frontend import tensorflow_graph_to_onnx_model

with tf.gfile.GFile("frozen_graph.pb", "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    onnx_model = tensorflow_graph_to_onnx_model(graph_def,
                                     "fc2/add",
                                     opset=6)

    file = open("mnist.onnx", "wb")
    file.write(onnx_model.SerializeToString())
    file.close()
```
But it looks that the ```tensorflow_graph_to_onnx_model``` only can deal with one output node with the ```output``` param. How to handle the situation that convert a tensorflow model with multiple output nodes? Thanks!

**Comment by fumihwh** [comment]
#204 Could you try this PR?

**Comment by fengshikun** [comment]
@fumihwh , very thanks, i have tired the branch, but another error occurs:
```
2018-06-06 08:39:56.632403: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/kun/Documents/Detection/MTCNN-Tensorflow/convert/convert_to_onnx.py", line 8, in <module>
    ["cls_prob", "bbox_pred"])
  File "/home/kun/.virtualenvs/cv/local/lib/python2.7/site-packages/onnx_tf-1.1.2-py2.7.egg/onnx_tf/frontend.py", line 400, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/home/kun/.virtualenvs/cv/local/lib/python2.7/site-packages/onnx_tf-1.1.2-py2.7.egg/onnx_tf/frontend.py", line 330, in tensorflow_graph_to_onnx_graph
    domain=None if node.domain in handlers else node.domain)
  File "/home/kun/.virtualenvs/cv/local/lib/python2.7/site-packages/onnx_tf-1.1.2-py2.7.egg/onnx_tf/common/exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "/home/kun/.virtualenvs/cv/local/lib/python2.7/site-packages/onnx_tf-1.1.2-py2.7.egg/onnx_tf/common/exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError: Pack is not implemented.
```

**Comment by fumihwh** [comment]
@fengshikun 
Try use ExpandDims and Concat instead of Pack.
Pack is not an ONNX op. You can find all ONNX op [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md)
And our frontend coverage [here](https://github.com/onnx/onnx-tensorflow/blob/master/doc/support_status.md)

BTW, if you don't want to run exported ONNX pb with other backend, `ignore_unimplemented` could help. 
API is [here](https://github.com/onnx/onnx-tensorflow/blob/master/doc/API.md#onnx_tffrontendtensorflow_graph_to_onnx_model)

**Comment by fengshikun** [comment]
@fumihwh , thanks!
