### ISSUE TITLE
RuntimeError: No schema registered for 'Asin'

### ISSUE THREAD

**Issue by InnerPeace-Wu** [onnx/onnx-tensorflow#233]
**Describe the bug**

Trying to convert a frozen graph to onnx, 
```python
with tf.gfile.GFile("train_log/frozen_graph.pb", "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        onnx_model = tensorflow_graph_to_onnx_model(graph_def,
                                                    "InceptionResnetV2/AuxLogits/Logits/BiasAdd",
                                                    opset=6)

        file = open("train_log/inception_resnet_v2.onnx", "wb")
        file.write(onnx_model.SerializeToString())
        file.close()

    print(onnx_model.graph.node[0])
```
but gives error:
```sh
Traceback (most recent call last):
  File "get_tf_net.py", line 46, in <module>
    tf_export_onnx()
  File "get_tf_net.py", line 35, in tf_export_onnx
    opset=6)
  File "/home/wuchangqiao/onnx-tensorflow/onnx_tf/frontend.py", line 399, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/home/wuchangqiao/onnx-tensorflow/onnx_tf/frontend.py", line 304, in tensorflow_graph_to_onnx_graph
    handlers = get_all_frontend_handlers(opset_dict)
  File "/home/wuchangqiao/onnx-tensorflow/onnx_tf/common/handler_helper.py", line 31, in get_all_frontend_handlers
    max_inclusive_version=version).since_version
RuntimeError: No schema registered for 'Asin'!
```

**tensorflow pb file**

If applicable, attach the onnx model file in question using Gist, DropBox or Google Drive.

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.5
 - ONNX version: 1.1.2
 - ONNX-TF version:1.1.2
 - Tensorflow version: 1.9

**Comment by fumihwh** [comment]
@InnerPeace-Wu 
The error is `RuntimeError: InceptionResnetV2/AuxLogits/Flatten/flatten/Reshape/shape of Reshape is not found in graph consts.!`
Means you are trying to export `Reshape` with dynamic shape attribute (such as a tensor), which is not supported in onnx-tf now.
![image](https://user-images.githubusercontent.com/6838753/43628453-4087857e-9735-11e8-8b7a-a6772cfe2c2d.png)

**Comment by bluemonk482** [comment]
@fumihwh Thanks Wenhao! I tried without adding `opset` but I got the error below and I am sure what is going on here:

```
In [2]: with tf.gfile.GFile("frozen_model.pb", "rb") as f:
   ...:     graph_def = tf.GraphDef()
   ...:     graph_def.ParseFromString(f.read())
   ...:     onnx_model = tensorflow_graph_to_onnx_model(graph_def, "output/Softmax", ignore_
   ...: unimplemented=True)
   ...:
2018-11-08 15:14:36.806890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0841:00:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-11-08 15:14:36.806933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-11-08 15:14:54.505821: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-08 15:14:54.505869: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2018-11-08 15:14:54.505887: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2018-11-08 15:14:54.551478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10758 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0841:00:00.0, compute capability: 3.7)
/home/ccrmad/.local/lib/python3.5/site-packages/onnx_tf/handlers/handler.py:35: UserWarning: Pack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/ccrmad/.local/lib/python3.5/site-packages/onnx_tf/common/handler_helper.py:38: UserWarning: Unknown op Undefined in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/home/ccrmad/.local/lib/python3.5/site-packages/onnx_tf/handlers/handler.py:35: UserWarning: Unpack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/ccrmad/.local/lib/python3.5/site-packages/onnx_tf/common/exception.py:15: UserWarning: StridedSlice is not implemented.
  self._func(self.get_message(*args, **kwargs))
/home/ccrmad/.local/lib/python3.5/site-packages/onnx_tf/handlers/frontend_handler.py:106: UserWarning: Skipped check for StridedSlice.
  warnings.warn("Skipped check for {}.".format(node.op_type))
/home/ccrmad/.local/lib/python3.5/site-packages/onnx_tf/common/exception.py:15: UserWarning: Range is not implemented.
  self._func(self.get_message(*args, **kwargs))
/home/ccrmad/.local/lib/python3.5/site-packages/onnx_tf/handlers/frontend_handler.py:106: UserWarning: Skipped check for Range.
  warnings.warn("Skipped check for {}.".format(node.op_type))
/home/ccrmad/.local/lib/python3.5/site-packages/onnx_tf/common/exception.py:15: UserWarning: GatherNd is not implemented.
  self._func(self.get_message(*args, **kwargs))
/home/ccrmad/.local/lib/python3.5/site-packages/onnx_tf/handlers/frontend_handler.py:106: UserWarning: Skipped check for GatherNd.
  warnings.warn("Skipped check for {}.".format(node.op_type))
/home/ccrmad/.local/lib/python3.5/site-packages/onnx_tf/common/exception.py:15: UserWarning: NotEqual is not implemented.
  self._func(self.get_message(*args, **kwargs))
/home/ccrmad/.local/lib/python3.5/site-packages/onnx_tf/handlers/frontend_handler.py:106: UserWarning: Skipped check for NotEqual.
  warnings.warn("Skipped check for {}.".format(node.op_type))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-fd2a16de5e5b> in <module>()
      2     graph_def = tf.GraphDef()
      3     graph_def.ParseFromString(f.read())
----> 4     onnx_model = tensorflow_graph_to_onnx_model(graph_def, "output/Softmax", ignore_unimplemented=True)
      5

~/.local/lib/python3.5/site-packages/onnx_tf/frontend.py in tensorflow_graph_to_onnx_model(cls, graph_def, output, opset, producer_name, graph_name, ignore_unimplemented, optimizer_passes)
    397
    398     onnx_graph = cls.tensorflow_graph_to_onnx_graph(
--> 399         graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
    400     onnx_model = make_model(
    401         onnx_graph, producer_name=producer_name, opset_imports=opset_imports)

~/.local/lib/python3.5/site-packages/onnx_tf/frontend.py in tensorflow_graph_to_onnx_graph(cls, graph_def, output, opset, name, ignore_unimplemented)
    322               consts=onnx_graph.consts,
    323               node_dict=dict(node_tup),
--> 324               data_type_cast_map=onnx_graph.data_type_cast_map)
    325         else:
    326           exception.OP_UNIMPLEMENTED_EXCEPT(

~/.local/lib/python3.5/site-packages/onnx_tf/handlers/handler.py in handle(cls, node, **kwargs)
     58     if ver_handle:
     59       cls.args_check(node, **kwargs)
---> 60       return ver_handle(node, **kwargs)
     61     exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type, cls.SINCE_VERSION)
     62     return None

~/.local/lib/python3.5/site-packages/onnx_tf/handlers/frontend/reduce_sum.py in version_1(cls, node, **kwargs)
     11   @classmethod
     12   def version_1(cls, node, **kwargs):
---> 13     return cls.reduction_op(node, **kwargs)

~/.local/lib/python3.5/site-packages/onnx_tf/handlers/frontend/math_mixin.py in reduction_op(cls, node, **kwargs)
     34         node, [node.inputs[0]],
     35         axes=axes,
---> 36         keepdims=node.attr.get("keep_dims", 1))

~/.local/lib/python3.5/site-packages/onnx_tf/handlers/frontend_handler.py in make_node_from_tf_node(cls, node, inputs, outputs, op_type, name, doc_string, version, should_check, **kwargs)
    100         name=name if name is not None else node.name,
    101         doc_string=doc_string,
--> 102         **kwargs)
    103     if should_check:
    104       cls.check_node(node, version)

/anaconda/envs/py35/lib/python3.5/site-packages/onnx/helper.py in make_node(op_type, inputs, outputs, name, doc_string, **kwargs)
     49         node.attribute.extend(
     50             make_attribute(key, value)
---> 51             for key, value in sorted(kwargs.items()))
     52     return node
     53

/anaconda/envs/py35/lib/python3.5/site-packages/onnx/helper.py in <genexpr>(.0)
     49         node.attribute.extend(
     50             make_attribute(key, value)
---> 51             for key, value in sorted(kwargs.items()))
     52     return node
     53

/anaconda/envs/py35/lib/python3.5/site-packages/onnx/helper.py in make_attribute(key, value, doc_string)
    209     # third, iterable cases
    210     elif is_iterable:
--> 211         byte_array = [_to_bytes_or_false(v) for v in value]
    212         if all(isinstance(v, float) for v in value):
    213             attr.floats.extend(value)

TypeError: iteration over a 0-d array
```

**Comment by bluemonk482** [comment]
Thanks @fumihwh ! I have installed `onnx` and `onnx-tf` both from source. However now I am getting assertionError : 

```
ccrmad@SpeechVM:~onnx-tf convert -t onnx -i frozen_model.pb -o frozen_model.onnx
/anaconda/envs/py35/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:root:Start converting tf pb to onnx pb:
2018-11-10 14:36:14.245114: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 51e7:00:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-11-10 14:36:14.245163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-11-10 14:36:29.625804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-10 14:36:29.625859: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2018-11-10 14:36:29.625878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2018-11-10 14:36:29.645892: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10758 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 51e7:00:00.0, compute capability: 3.7)
Traceback (most recent call last):
  File "/anaconda/envs/py35/bin/onnx-tf", line 11, in <module>
    sys.exit(main())
  File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/cli.py", line 18, in main
    return onnx_tf.converter.main(args[1:])
  File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/converter.py", line 20, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/converter.py", line 183, in convert
    graph_def, get_output_node_names(graph_def), **kwargs)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/frontend.py", line 160, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/frontend.py", line 85, in tensorflow_graph_to_onnx_graph
    data_type_cast_map=onnx_graph.data_type_cast_map)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/handlers/frontend_handler.py", line 41, in handle
    return super(FrontendHandler, cls).handle(node, **kwargs)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/handlers/frontend/strided_slice.py", line 35, in version_9
    assert only_support, "limited strided slice support"
AssertionError: limited strided slice support
```

**Comment by tjingrant** [comment]
@bluemonk482 we did not implement full support for strided slice because:

1. Implementing full support for strided slice is difficult and
2. We didn't see a good use case for strided slice beyond what is currently supported.

So if you can share your model/application scenario with us, we can decide whether we should add more support for strided slice.

**Comment by iamshri8** [comment]
I have developed a Keras model for semantic segmentation of street images. So, first i converted my Keras model to .pb file. And now i am trying to convert it to onnx. 

def unet(num_classes, in_shape, lrate, decay_rate):
    in_img = Input(in_shape)

    # Down sampling block 1
    x = Conv2D(64, (3, 3), padding='same')(in_img)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(64, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    block1 = Activation('relu')(x)

    x = MaxPooling2D()(block1)

    # Down sampling block 2
    x = Conv2D(128, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(128, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    block2 = Activation('relu')(x)

    x = MaxPooling2D()(block2)

    # Down sampling block 3
    x = Conv2D(256, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(256, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(256, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    block3 = Activation('relu')(x)

    x = MaxPooling2D()(block3)

    # Down sampling block 4
    x = Conv2D(512, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(512, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(512, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    block4 = Activation('relu')(x)

    x = MaxPooling2D()(block4)

    # Bottleneck block
    x = Conv2D(512, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(512, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(512, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    # Up sampling 1
    x = Conv2DTranspose(512, (2, 2), strides=(2, 2), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = concatenate([x, block4])
    x = Conv2D(512, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(512, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    # Up sampling 2
    x = Conv2DTranspose(256, (2, 2), strides=(2, 2), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = concatenate([x, block3])
    x = Conv2D(256, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(256, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    # Up sampling 3
    x = Conv2DTranspose(128, (2, 2), strides=(2, 2), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = concatenate([x, block2])
    x = Conv2D(128, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(128, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    # Up sampling 4
    x = Conv2DTranspose(64, (2, 2), strides=(2, 2), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = concatenate([x, block1])
    x = Conv2D(64, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(64, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    # last convolution
    output = Conv2D(num_classes, (3, 3), activation='softmax', padding='same', name='output')(x)

    # instantiate the model variables
    model = Model(inputs=in_img, outputs=output)

    # onnx_model = onnxmltools.convert_keras(model, target_opset=7)

    #configure the model for training
    model.compile(optimizer=Adam(lr=lrate, decay=decay_rate),
                  loss='categorical_crossentropy')

    return model

Let me know if any further details are required , I will provide the same.

**Comment by iamshri8** [comment]
I am getting Strided Slice error while running mnist model as well.

**Comment by Varusnguyen** [comment]
> Thanks @fumihwh ! I have installed `onnx` and `onnx-tf` both from source. However now I am getting assertionError :
> 
> ```
> ccrmad@SpeechVM:~onnx-tf convert -t onnx -i frozen_model.pb -o frozen_model.onnx
> /anaconda/envs/py35/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> INFO:root:Start converting tf pb to onnx pb:
> 2018-11-10 14:36:14.245114: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
> name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
> pciBusID: 51e7:00:00.0
> totalMemory: 11.17GiB freeMemory: 11.10GiB
> 2018-11-10 14:36:14.245163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
> 2018-11-10 14:36:29.625804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-11-10 14:36:29.625859: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
> 2018-11-10 14:36:29.625878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
> 2018-11-10 14:36:29.645892: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10758 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 51e7:00:00.0, compute capability: 3.7)
> Traceback (most recent call last):
>   File "/anaconda/envs/py35/bin/onnx-tf", line 11, in <module>
>     sys.exit(main())
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/cli.py", line 18, in main
>     return onnx_tf.converter.main(args[1:])
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/converter.py", line 20, in main
>     convert(**{k: v for k, v in vars(args).items() if v is not None})
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/converter.py", line 183, in convert
>     graph_def, get_output_node_names(graph_def), **kwargs)
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/frontend.py", line 160, in tensorflow_graph_to_onnx_model
>     graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/frontend.py", line 85, in tensorflow_graph_to_onnx_graph
>     data_type_cast_map=onnx_graph.data_type_cast_map)
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/handlers/frontend_handler.py", line 41, in handle
>     return super(FrontendHandler, cls).handle(node, **kwargs)
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/handlers/handler.py", line 60, in handle
>     return ver_handle(node, **kwargs)
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/onnx_tf/handlers/frontend/strided_slice.py", line 35, in version_9
>     assert only_support, "limited strided slice support"
> AssertionError: limited strided slice support
> ```
Hi, @bluemonk482  Can you please tell me how to install onnx from the source. I always use pip install onnx to implement the onnx to my computer. Im sorry to ask that such of easily question, because Im a begginer for this kind of knowledge.

**Comment by Varusnguyen** [comment]
Hi everyone. I am trying to convert the tensorflow model to onnx model using the following code. I tried some above suggestions but it was not worked for me so far.  I got the an error as following: 
![image](https://user-images.githubusercontent.com/49540574/57059402-c3384200-6ce7-11e9-8907-6d20390de0a3.png)
Here is my code: 

import tensorflow as tf
from onnx_tf.frontend import tensorflow_graph_to_onnx_model

with tf.gfile.GFile("tf_model.pb", "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        onnx_model = tensorflow_graph_to_onnx_model(graph_def,
                                                    "dense_2/BiasAdd",
                                                    opset=6,
                                                    ignore_unimplemented=True)

        file = open("train_log/inception_resnet_v2.onnx", "wb")
        file.write(onnx_model.SerializeToString())
        file.close()
