### ISSUE TITLE
KeyError: dtype('O') when converting BiDAF graph to ONNX

### ISSUE THREAD

**Issue by jack9766** [onnx/onnx-tensorflow#237]
**Describe the bug**

Got `KeyError: dtype('O')` when trying to convert frozen [BiDAF](https://github.com/allenai/bi-att-flow/tree/dev) graph to ONNX.

Full stacktrace:
```shell
Traceback (most recent call last):
  File "tf2onnx.py", line 18, in <module>
    ignore_unimplemented=True)
  File "/home/j84095329/tf2onnx/onnx-tensorflow/onnx_tf/frontend.py", line 399, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/home/j84095329/tf2onnx/onnx-tensorflow/onnx_tf/frontend.py", line 306, in tensorflow_graph_to_onnx_graph
    node_tup = [(node.name, TensorflowNode(node)) for node in graph_def.node]
  File "/home/j84095329/tf2onnx/onnx-tensorflow/onnx_tf/frontend.py", line 306, in <listcomp>
    node_tup = [(node.name, TensorflowNode(node)) for node in graph_def.node]
  File "/home/j84095329/tf2onnx/onnx-tensorflow/onnx_tf/frontend.py", line 48, in __init__
    new_val = attr_translator.translate_tf(key, val)
  File "/home/j84095329/tf2onnx/onnx-tensorflow/onnx_tf/common/attr_translator.py", line 28, in translate_tf
    return __tf_attr_translator.get(key, lambda x: x)(val)
  File "/home/j84095329/tf2onnx/onnx-tensorflow/onnx_tf/common/attr_translator.py", line 10, in <lambda>
    "dtype": lambda x: data_type.tf2onnx(x.type),
  File "/home/j84095329/tf2onnx/onnx-tensorflow/onnx_tf/common/data_type.py", line 16, in tf2onnx
    return mapping.NP_TYPE_TO_TENSOR_TYPE[np.dtype(tf_dype.as_numpy_dtype)]
KeyError: dtype('O')
```

**To Reproduce**

I can not publish the frozen graph I used. But here is the script:

```python
import tensorflow as tf
from onnx_tf.frontend import tensorflow_graph_to_onnx_model

with tf.gfile.GFile("frozen_basic.pb", "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    onnx_model = tensorflow_graph_to_onnx_model(graph_def,
                                     ["model_0/OutputLayer/Softmax", "model_0/OutputLayer/Softmax_1"],
                                     opset=7,
                                     ignore_unimplemented=True)

    print(set(n.op_type for n in onnx_model.graph.node))

    fo = open("lstm.onnx", "wb")
    fo.write(onnx_model.SerializeToString())
    fo.close()
```

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 
```
3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:43)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
```
 - ONNX version: `1.2.2`
 - ONNX-TF version: `1.1.2`
 - Tensorflow version:  `1.10.0`

**Comment by jack9766** [comment]
The problem is the tf_type is of `<dtype: 'string'>`.
and `np.dtype` returns `<class 'object'>`
then `NP_TYPE_TO_TENSOR_TYPE` can not handle object type.

Maybe add string type support to onnx?

**Comment by jack9766** [comment]
I noticed onnx already supports STRING. so I added the following fix in `onnx-tensorflow/onnx_tf/common/data_type.py`

```python
if tf_dype is tf.string:
    return TensorProto.STRING
```

**Comment by tjingrant** [comment]
Thanks, fix is on the way. But since we have not tested extensively for the string type, I suspect this may not be the only problem you will face with string type. Please let us know if you have any follow up issues.

**Comment by tjingrant** [comment]
Closing as no response has been received.

**Comment by jack9766** [comment]
There is a bug with the fix, heres the original fix:

```python
def tf2onnx(dtype):
  if isinstance(dtype, Number):
    tf_dype = tf.as_dtype(dtype)
  elif isinstance(dtype, tf.DType):
    # Usually, tf2onnx is done via tf_type->numpy_type->onnx_type
    # to leverage existing type conversion infrastructure;
    # However, we need to intercept the string type early because
    # lowering tf.string type to numpy dtype results in loss of
    # information. <class 'object'> is returned instead of the
    # numpy string type desired.
    if tf_dype is tf.string:
      return TensorProto.STRING
    else:
      tf_dype = dtype
  else:
    raise RuntimeError("dtype should be number or tf.DType.")
  return mapping.NP_TYPE_TO_TENSOR_TYPE[np.dtype(tf_dype.as_numpy_dtype)]
```

Here is what it should be:

```python
def tf2onnx(dtype):
  if isinstance(dtype, Number):
    tf_dype = tf.as_dtype(dtype)
  elif isinstance(dtype, tf.DType):
    tf_dype = dtype
  else:
    raise RuntimeError("dtype should be number or tf.DType.")

  if tf_dype is tf.string:
    return TensorProto.STRING

  return mapping.NP_TYPE_TO_TENSOR_TYPE[np.dtype(tf_dype.as_numpy_dtype)]
```

if dtype is tf.STRING as Number (7 for tf.STRING) the error this issue mentioned will happen again.

**Comment by tjingrant** [comment]
Done in the new PR. Can you verify? https://github.com/onnx/onnx-tensorflow/pull/245

Hope you understand that I'm doing a lot of guess work here since I can't just test it out by running...

**Comment by jack9766** [comment]
Yep that would work.
