### ISSUE TITLE
When converting tf model to onnx: get"RuntimeError: No schema registered for 'Acos'!"

### ISSUE THREAD

**Issue by peteryang1** [onnx/onnx-tensorflow#278]
When I convert a tensorflow model to onnx model, the error below occurs:
==

Traceback (most recent call last):
  File ".\tf2onnx_convertor.py", line 32, in <module>
    tf2onnx('.\\ckpt\\inception_v2.pb','result','.\\ckpt')
  File ".\tf2onnx_convertor.py", line 14, in tf2onnx
    opset=6)
  File "D:\software\python3.6\lib\site-packages\onnx_tf-1.2.0-py3.6.egg\onnx_tf\frontend.py", line 399, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "D:\software\python3.6\lib\site-packages\onnx_tf-1.2.0-py3.6.egg\onnx_tf\frontend.py", line 304, in tensorflow_graph_to_onnx_graph
    handlers = get_all_frontend_handlers(opset_dict)
  File "D:\software\python3.6\lib\site-packages\onnx_tf-1.2.0-py3.6.egg\onnx_tf\common\handler_helper.py", line 31, in get_all_frontend_handlers
    max_inclusive_version=version).since_version
RuntimeError: No schema registered for 'Acos'!

**To Reproduce**

the python script:
```Python
    with tf.gfile.GFile(".\\add_model.pb", "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        onnx_model = tensorflow_graph_to_onnx_model(graph_def,
                                        "predictions",
                                        opset=6)
```

Please give us instructions to reproduce your problem.

A __self-contained__ piece of code that can demonstrate the problem is required.

tensorflow model file:
===

[add_model.zip](https://github.com/onnx/onnx-tensorflow/files/2463840/add_model.zip)

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6.6
 - ONNX version: 1.3.0
 - ONNX-TF version:1.2.0
 - Tensorflow version: 1.11.0

**Comment by fumihwh** [comment]
@peteryang1 Acos is added from opset 7. ad hoc fix will be remove `opset=6` from your code if there is no particular reason.

**Comment by fumihwh** [comment]
@tjingrant I would like to use a `try` block to catch the exception first.
Second, change the code that warning user only their graph has corresponding node.

**Comment by iamshri8** [comment]
When I convert a tensorflow model to onnx model, the error below occurs: 

Rathna-Air:master_project ratzzz$ python3 tensorflow_to_onnx.py
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx_tf/common/__init__.py:87: UserWarning: FrontendHandler.get_outputs_names is deprecated. It will be removed in future release.. Use node.outputs instead.
  warnings.warn(message)
2019-01-08 15:29:51.579402: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "tensorflow_to_onnx.py", line 13, in <module>
    "conv2d_22/truediv", opset=6)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx_tf/frontend.py", line 175, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx_tf/frontend.py", line 70, in tensorflow_graph_to_onnx_graph
    handlers = get_all_frontend_handlers(opset_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx_tf/common/handler_helper.py", line 30, in get_all_frontend_handlers
    max_inclusive_version=version).since_version
RuntimeError: No schema registered for 'Acos'!

Python script is - 

with tf.gfile.GFile("saved_model/model.pb", "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    onnx_model = tensorflow_graph_to_onnx_model(graph_def,
                                     "conv2d_22/truediv", opset=6)

**Comment by fumihwh** [comment]
@iamshri8 Do you have especial reason to use `opset=6`? If not, remove this attr.

**Comment by fumihwh** [comment]
@iamshri8 Set `opset` will let onnx-tf to export an ONNX graph with that `opset`. You should make sure that your tf graph doesn't contain any OP supported by `opset` later.
Check https://github.com/onnx/onnx/blob/master/docs/Versioning.md for more information about ONNX versioning.

**Comment by iamshri8** [comment]
If i remove opset from my code, 

with tf.gfile.GFile("saved_model/model.pb", "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    onnx_model = tensorflow_graph_to_onnx_model(graph_def,
                                     "conv2d_22/truediv")

I am getting the following error.
Traceback (most recent call last):
  File "tensorflow_to_onnx.py", line 13, in <module>
    "conv2d_22/truediv")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx_tf/frontend.py", line 175, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx_tf/frontend.py", line 100, in tensorflow_graph_to_onnx_graph
    data_type_cast_map=onnx_graph.data_type_cast_map)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx_tf/handlers/frontend_handler.py", line 41, in handle
    return super(FrontendHandler, cls).handle(node, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx_tf/handlers/handler.py", line 61, in handle
    exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type, cls.SINCE_VERSION)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx_tf/common/exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/onnx_tf/common/exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError: StridedSlice version 1 is not implemented.

**Comment by iamshri8** [comment]
Can someone help me on this?

**Comment by iamshri8** [comment]
@fumihwh Thank you for the reply.

Could you please tell steps for installing onnx from source ?

**Comment by iamshri8** [comment]
@tjingrant Thanks for the link.

Please find the attached screenshots. Both of them tell after installing protobuf, we need to install onnx via Pypi. 

Intially i just did pip install onnx and pip install onnx-tf. 

So, I am little confused.
Could you please confirm on this?
![capture](https://user-images.githubusercontent.com/31486526/51085473-34a0b480-173a-11e9-9aeb-cde76416eaa9.PNG)
![capture1](https://user-images.githubusercontent.com/31486526/51085474-35394b00-173a-11e9-98b7-5a002dfcfe16.PNG)

**Comment by iamshri8** [comment]
@fumihwh @tjingrant 
I installed protobuf by pip as well. So, I am getting strided slice error. 

So, in the above 2 screenshots, which one should i follow to resolve my stridedslice error?

**Comment by iamshri8** [comment]
@fumihwh @tjingrant 

While trying to install onnx from source by following the below steps:

git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
python setup.py install

**I am getting AssertionError : Could not find "cmake" executable!.**

Could you please help me on this?

**Comment by tjingrant** [comment]
Hi @iamshri8 you are on the right track, I believe onnx source installation requires cmake. Depending on your OS, there are various ways to get that installed. For instance, on Mac, doing a `brew install cmake` would suffice.

That being said, I would also like to remind you that you are getting into troubles of installing onnx, not onnx-tf. So we can still try to help as much as we could based on our experience using onnx, but bear in mind that we are not primary authors behind ONNX and this repository is about ONNX-Tensorflow.

**Comment by iamshri8** [comment]
@tjingrant Thank you for your solution. It worked (y). 

I used the following script for converting tensorflow model to onnx:

**from tensorflow.core.framework import graph_pb2

from onnx_tf.frontend import tensorflow_graph_to_onnx_model
from onnx_tf.pb_wrapper import TensorflowGraph

graph_def = graph_pb2.GraphDef()
with open("saved_model/model.pb", "rb") as f:  # load tf graph def
  graph_def.ParseFromString(f.read())
output = TensorflowGraph.get_output_node_names(
    graph_def)  # get output node names

model = tensorflow_graph_to_onnx_model(graph_def,
                                       output)  # convert tf graph to onnx model
with open("saved_model/semantic1.onnx", 'wb') as f:
  f.write(model.SerializeToString())**

While running this, I am getting the following error:

![screen shot 2019-01-14 at 1 46 59 am](https://user-images.githubusercontent.com/31486526/51092977-55025a80-179e-11e9-976f-8386cf023fba.png)
