### ISSUE TITLE
NotImplementedError on multiple ops

### ISSUE THREAD

**Issue by blagodurov** [onnx/onnx-tensorflow#291]
I am trying to convert multiple frozen_graph .pb files into .onnx files. The frozen graph .pb files were generated in two ways:

1. from .onnx file with:
```
tf_rep = prepare(model)
tf_rep.export_graph('file.pb')
```

2. From SavedModel Tensorflow format with tf.graph_util.convert_variables_to_constants()

I use tensorflow_graph_to_onnx_model to convert to .onnx. I see the following errors:

Traceback (most recent call last):
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 399, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 328, in tensorflow_graph_to_onnx_graph
    domain=None if node.domain in handlers else node.domain)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/common/exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/common/exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError: PadV2 is not implemented.
NotImplementedError: Rsqrt is not implemented.
NotImplementedError: ReadFile is not implemented.
NotImplementedError: PyFunc is not implemented.
NotImplementedError: StopGradient is not implemented.
NotImplementedError: Where is not implemented.
NotImplementedError: LRN is not implemented.
NotImplementedError: StridedSlice version 1 is not implemented.

Just wanted to ask: which ones of these are training related? Do you think you could add support for the rest of the ops? Thank you!

**Comment by fumihwh** [comment]
@blagodurov 
First, ONNX doesn't support `ReadFile`, `StopGradient`, `Where`, of course `PyFunc`, now. But you could use `ignore_unimplemented` to ignore these. Take care the exported model is not an ONNX model strictly (contains unsupported op and can't pass the check).

Second, I don't try yet but `PadV2`, `LRN`, `Rsqrt` should be OK.
And limited `StridedSlice` is added from opset v9 because it uses `DynamicSlice` which is added to ONNX from opset v9.

**Comment by blagodurov** [comment]
@fumihwh Thank you for your help! Now I use the following invocation to convert to .onnx:
`tensorflow_graph_to_onnx_model(graph_def, output_node_names, ignore_unimplemented=True)`

1. I see that ignore_unimplemented=True helped for most of the frozen_graph .pb files generated with
```
tf_rep = prepare(model)
tf_rep.export_graph('file.pb')

```
Except for one .pb file that gave the following error:
```
/notebooks/onnx-tensorflow-master/onnx_tf/common/exception.py:15: UserWarning: PyFunc is not implemented.
  self._func(self.get_message(*args, **kwargs))
/notebooks/onnx-tensorflow-master/onnx_tf/handlers/frontend_handler.py:106: UserWarning: Skipped check for PyFunc.
  warnings.warn("Skipped check for {}.".format(node.op_type))
Traceback (most recent call last):
  File "<stdin>", line 32, in <module>
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 399, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 324, in tensorflow_graph_to_onnx_graph
    data_type_cast_map=onnx_graph.data_type_cast_map)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/handlers/frontend/reduce_sum.py", line 13, in version_1
    return cls.reduction_op(node, **kwargs)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/handlers/frontend/math_mixin.py", line 36, in reduction_op
    keepdims=node.attr.get("keep_dims", 1))
  File "/notebooks/onnx-tensorflow-master/onnx_tf/handlers/frontend_handler.py", line 102, in make_node_from_tf_node
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/onnx/helper.py", line 51, in make_node
    for key, value in sorted(kwargs.items()))
  File "/usr/local/lib/python2.7/dist-packages/onnx/helper.py", line 51, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "/usr/local/lib/python2.7/dist-packages/onnx/helper.py", line 227, in make_attribute
    byte_array = [_to_bytes_or_false(v) for v in value]
TypeError: iteration over a 0-d array
```
I assume this is because of custom PyFunc in it?

2. As for the frozen_graph .pb files generated from SavedModel Tensorflow format with tf.graph_util.convert_variables_to_constants(), I now see this error:
```
/notebooks/onnx-tensorflow-master/onnx_tf/handlers/handler.py:35: UserWarning: Pack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/notebooks/onnx-tensorflow-master/onnx_tf/common/handler_helper.py:38: UserWarning: Unknown op Undefined in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/notebooks/onnx-tensorflow-master/onnx_tf/handlers/handler.py:35: UserWarning: Relu6 doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/notebooks/onnx-tensorflow-master/onnx_tf/common/handler_helper.py:38: UserWarning: Unknown op DynamicSlice in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/notebooks/onnx-tensorflow-master/onnx_tf/handlers/handler.py:35: UserWarning: Unpack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/notebooks/onnx-tensorflow-master/onnx_tf/common/exception.py:15: UserWarning: StridedSlice version 1 is not implemented.
  self._func(self.get_message(*args, **kwargs))
/notebooks/onnx-tensorflow-master/onnx_tf/handlers/frontend_handler.py:106: UserWarning: Skipped check for StridedSlice.
  warnings.warn("Skipped check for {}.".format(node.op_type))
Traceback (most recent call last):
  File "<stdin>", line 31, in <module>
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 399, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 316, in tensorflow_graph_to_onnx_graph
    onnx_graph.add_value_info_proto(node)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 193, in add_value_info_proto
    for i, output_shape in enumerate(node.attr["_output_shapes"]):
KeyError: u'_output_shapes'
```
Please note that I do use add_shapes=True when generating those .pb files:
```
graph_def = sess.graph.as_graph_def(add_shapes=True)
output_graph_def = tf.graph_util.convert_variables_to_constants(sess, graph_def, output_node_names, None, None) 

```
I appreciate your help!

**Comment by fumihwh** [comment]
@blagodurov 
#296 will fix first error `TypeError: iteration over a 0-d array`.

Could you try `str("_output_shapes")` or `"_output_shapes".encode("ascii")`  in frontend.py L193?
```
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 193, in add_value_info_proto
    for i, output_shape in enumerate(node.attr["_output_shapes"]):
KeyError: u'_output_shapes'
```

**Comment by fumihwh** [comment]
@blagodurov I see. It's not the key problem. Seems the node `init` doesn't have `_output_shapes`.
Could you give a simple sample pb for this problem?

**Comment by fumihwh** [comment]
@blagodurov Which did you use, `init_net.pb` or `predict_net.pb`? I saw lots of `Assign` nodes in graph. Maybe you use `init_net.pb`?
Could you try `predict_net.pb`?

**Comment by fumihwh** [comment]
@blagodurov Thanks~
I am confused about your purpose.
Do you want to do Caffe2 -> Tensorflow -> ONNX? If true, why don't you try Caffe2 -> ONNX?

Maybe you have your own reason, so the pb here https://www.dropbox.com/s/5tbabr6du5kc61v/bvlc_googlenet.pb?dl=0 is converted by mmdnn?
