### ISSUE TITLE
NotImplementedError: ResizeBilinear is not implemented.

### ISSUE THREAD

**Issue by hondaathma** [onnx/onnx-tensorflow#339]
I get the error NotImplementedError: ResizeBilinear is not implemented when trying to convert my model from TF. 

Python version:
2.7.6 (default, Nov 13 2018, 12:45:42)
[GCC 4.8.4]
ONNX version:
1.3.0
ONNX-TF version:
1.2.0
Tensorflow version:
1.4.0

The steps I tried was to create a new file called resizebilinear.py in   onnx-tensorflow/onnx_tf/handlers/frontend folder and added the following in the file: 

```
import copy

import numpy as np
import tensorflow as tf

from onnx_tf.common import exception
from onnx_tf.handlers.backend_handler import BackendHandler
from onnx_tf.handlers.handler import onnx_op
from onnx_tf.handlers.handler import tf_func


@onnx_op("ResizeBilinear")
@tf_func(tf.image.resize_images)
class ResizeBilinear(BackendHandler):

  @classmethod
  def args_check(cls, node, **kwargs):
    x = kwargs["tensor_dict"][node.inputs[0]]
    x_shape = x.get_shape().as_list()
    if len(x_shape) != 4:
      exception.OP_UNSUPPORTED_EXCEPT("Upsample without 4D input", "Tensorflow")

    # if node.attrs.get("mode", "nearest").lower() not in ["nearest", "bilinear"]:
    #   exception.OP_UNSUPPORTED_EXCEPT("Upsample without nearest or bilinear",
    #                                   "Tensorflow")

  @classmethod
  def version_7(cls, node, **kwargs):
    x = kwargs["tensor_dict"][node.inputs[0]]
    x_shape = x.get_shape().as_list()
    attrs = copy.deepcopy(node.attrs)
    scales = attrs["scales"]
    new_height = np.floor(x_shape[2] * scales[2])
    new_weight = np.floor(x_shape[3] * scales[3])

    mode = attrs.get("mode", "nearest")
    # if mode.lower() == "bilinear":
    mode = tf.image.ResizeMethod.BILINEAR
    # else:
    #   mode = tf.image.ResizeMethod.NEAREST_NEIGHBOR

    attrs["size"] = np.array((new_height, new_weight), dtype=np.int32)
    attrs["method"] = mode

    return [
        cls.make_tensor_from_onnx_node(
            node, attrs=attrs, c_last_only=True, **kwargs)

```
But this does not resolve the error.

**Comment by hondaathma** [comment]
H @tjingrant..I saw that is was merged . However I still have this problem.
NotImplementedError: ResizeBilinear version 7 is not implemented.



So I added a new class  method under resize_blinear.py  for version 7:

```
  @classmethod
  def version_7(cls, node, **kwargs):
    unique_suffix = get_unique_suffix()

    # Convert to NCHW:
    transpose_node = Transpose.handle(
        TensorflowNode(
            name='transopose_input_to_nchw_' + unique_suffix,
            inputs=node.inputs[:1] + ["perm"],
            outputs=["transposed_input_" + unique_suffix]),
        consts={"perm": [0, 3, 1, 2]})

    # Get shape of NCHW input tensor:
    input_shape_node = Shape.handle(
        TensorflowNode(
            name='get_input_shape_' + unique_suffix,
            inputs=transpose_node.output,
            outputs=["input_shape_" + unique_suffix],
            attr=node.attr))

    util_one = OnnxGraph.CONST_ONE_FP32

    output_shape_tensor = node.inputs[1]

    # Cast output shape (HW dim only) to float32:
    out_shape_float = Cast.handle(
        TensorflowNode(
            name='cast_output_shape_to_fp32_' + unique_suffix,
            inputs=[output_shape_tensor],
            outputs=["output_shape_float_partial_" + unique_suffix],
            attr={"DstT": tf.float32}))

    # Cast input shape to float32:
    in_shape_cast = Cast.handle(
        TensorflowNode(
            name='cast_input_shape_to_fp32_' + unique_suffix,
            inputs=input_shape_node.output,
            outputs=["input_shape_float_" + unique_suffix],
            attr={"DstT": tf.float32}))

    slice_const_items = [
        ("begin", np.array([2]).astype(np.int32)),
        ("end", np.array([4]).astype(np.int32)),
        ("strides", np.array([1]).astype(np.int32)),
    ]

    slice_const_proto = {}

    for k, v in slice_const_items:
      const_name = "{}_".format(k) + unique_suffix
      slice_const_proto[k] = make_node(
          "Constant", [], [const_name],
          value=make_tensor(
              const_name, any_dtype_to_onnx_dtype(np_dtype=v.dtype), v.shape,
              v))

    in_shape_slices = StridedSlice.handle(
        TensorflowNode(
            name="stridedslice_input_shape_" + unique_suffix,
            inputs=list(in_shape_cast.output) +
            [slice_const_proto[k].output[0] for k, v in slice_const_items],
            outputs=["sliced_input_shape_" + unique_suffix]),
        consts={
            slice_const_proto[k].output[0]: v for k, v in slice_const_items
        },
        add_consts=True)

    # Divide input shape with output shape to get scaling factor:
    div_node = Div.handle(
        TensorflowNode(
            name='div_to_get_scale_factor_' + unique_suffix,
            inputs=list(out_shape_float.output) + list(
                in_shape_slices[-1].output),
            outputs=["hw_scale_" + unique_suffix]))

    # Prepend 1's in the N, C dimension:
    full_scale = Concat.handle(
        TensorflowNode(
            name='prepend_ones_to_scale_factor_' + unique_suffix,
            inputs=[util_one, util_one] + list(div_node.output) +
            ["concat_axis"],
            outputs=["scale_" + unique_suffix]),
        consts={"concat_axis": 0})

    # Upsample with the computed scaling factor:
    upsample_node = cls.make_node_from_tf_node(
        node,
        op_type="Upsample",
        mode="bilinear",
        inputs=list(transpose_node.output) + list(full_scale.output),
        outputs=["upsample_to_tranpose_" + unique_suffix])

    # Transpose back to NHWC:
    transpose_output_node = Transpose.handle(
        TensorflowNode(
            name='transpose_output_to_nhwc_' + unique_suffix,
            inputs=list(upsample_node.output) + ["perm"],
            outputs=node.outputs),
        consts={"perm": [0, 2, 3, 1]})

    transpose_and_get_shapes = [
        transpose_node, input_shape_node, out_shape_float, in_shape_cast
    ]
    slice_shape = list(slice_const_proto.values()) + in_shape_slices
    get_scale_and_upsample_and_transpose = [
        div_node, full_scale, upsample_node, transpose_output_node
    ]

    return transpose_and_get_shapes + slice_shape + get_scale_and_upsample_and_transpose

```


But this gives a weird error below:

```

 File "example/tf_to_onnx.py", line 12, in <module>
    model = tensorflow_graph_to_onnx_model(graph_def, output)  # convert tf graph to onnx model
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/frontend.py", line 175, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/frontend.py", line 100, in tensorflow_graph_to_onnx_graph
    data_type_cast_map=onnx_graph.data_type_cast_map)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/frontend_handler.py", line 41, in handle
    return super(FrontendHandler, cls).handle(node, **kwargs)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/frontend/resize_bilinear.py", line 202, in version_7
    add_consts=True)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/frontend_handler.py", line 41, in handle
    return super(FrontendHandler, cls).handle(node, **kwargs)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py", line 61, in handle
    exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type, cls.SINCE_VERSION)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/common/exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/common/exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError:  version 1 is not implemented.

```

Any ideas on how to solve this?

**Comment by tjingrant** [comment]
@hondaathma is it possible to upload an example model where I can reproduce this failure?

Otherwise, looking at your error msg, i'm guessing you did not install onnx from source. ResizeBilinear requires you to install ONNX from source because we used experimental ops in ONNX to implement it.

**Comment by hondaathma** [comment]
Hi @tjingrant  an hour after installing onnx from source provides the same error. I forgot to add these additional warnings on the top:
```
UserWarning: Unknown op Acosh in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/common/handler_helper.py:37: UserWarning: Unknown op Asinh in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/common/handler_helper.py:37: UserWarning: Unknown op Atanh in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/common/handler_helper.py:37: UserWarning: Unknown op Cosh in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: FloorDiv doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/common/handler_helper.py:37: UserWarning: Unknown op Undefined in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: Pack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: Relu6 doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/common/handler_helper.py:37: UserWarning: Unknown op DynamicSlice in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: Rsqrt doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/common/handler_helper.py:37: UserWarning: Unknown op Sinh in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: Square doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: Unpack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))

```

This is a semantic segmentation module which I wrote in tensorflow and converted to a .pb file. I have added it here: Please let me know how you think we can fix this because this is an operation that is widely used in semantic segmentation.

Link to download model: https://drive.google.com/file/d/1fag6cLvR7qOzAGv5NC1tuamlj4BgvusL/view?usp=sharing

**Comment by fumihwh** [comment]
@hondaathma 
If you install onnx from source (master branch),  warnings like `UserWarning: Unknown op Asinh in domain `ai.onnx`.` should not occur.

**Comment by hondaathma** [comment]
@fumihwh @tjingrant 
Sorry those warnings happened before installing onnx from source.. I dont get those warnings after installing onnx from source. 

However I do get a different set of  warnings after onnx install from source:

```
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: FloorDiv doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/common/handler_helper.py:37: UserWarning: Unknown op Undefined in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: Pack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: Relu6 doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: Rsqrt doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: Square doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py:35: UserWarning: Unpack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
Traceback (most recent call last):
  File "example/tf_to_onnx.py", line 12, in <module>
    model = tensorflow_graph_to_onnx_model(graph_def, output)  # convert tf graph to onnx model
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/frontend.py", line 175, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/frontend.py", line 100, in tensorflow_graph_to_onnx_graph
    data_type_cast_map=onnx_graph.data_type_cast_map)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/frontend_handler.py", line 41, in handle
    return super(FrontendHandler, cls).handle(node, **kwargs)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/frontend/resize_bilinear.py", line 91, in version_9
    add_consts=True)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/frontend_handler.py", line 41, in handle
    return super(FrontendHandler, cls).handle(node, **kwargs)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/handlers/handler.py", line 61, in handle
    exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type, cls.SINCE_VERSION)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/common/exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "/home/anarayanan/tensorflowC++/onnx-tensorflow/onnx_tf/common/exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError:  version 1 is not implemented.
```

I removed the pip install onnx and followed the below steps:
```
git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
sudo python2.7 setup.py install
```

And as far as I know the onnx installs properly without warnings or errors.

**Comment by hondaathma** [comment]
@fumihwh @tjingrant Any update guys?

**Comment by hondaathma** [comment]
I this this is related to #352 . Adding 
```

  @classmethod
  def version_1(cls, node, **kwargs):
    begin_mask = node.attr.get("begin_mask", 0)
    end_mask = node.attr.get("end_mask", 0)
    ellipsis_mask = node.attr.get("ellipsis_mask", 0)
    new_axis_mask = node.attr.get("new_axis_mask", 0)
    shrink_axis_mask = node.attr.get("shrink_axis_mask", 0)

    only_support = (int(begin_mask) is 0 and int(end_mask) is 0 and
                    int(ellipsis_mask) is 0 and int(new_axis_mask) is 0)
    assert only_support, "limited strided slice support"

    # Assert that strides are all ones, since we have limited support.
    const_strides = kwargs["consts"][node.inputs[3]]
    np.testing.assert_array_equal(np.ones_like(const_strides), const_strides)

    need_post_processing = (shrink_axis_mask > 0 or begin_mask > 0 or
                            end_mask > 0 or ellipsis_mask > 0 or
                            new_axis_mask > 0 or shrink_axis_mask > 0)

    slice_suffix = "_" + get_unique_suffix() if need_post_processing else ""
    slice_output_name = node.outputs[0]
    slice_node = cls.make_node("DynamicSlice", node.inputs[0:3],
                               [slice_output_name + slice_suffix],
                               node.name + slice_suffix)

    if not need_post_processing:
      return [slice_node]

    shrink_axis = cls._int_to_set_pos_list(shrink_axis_mask)
    squeeze_node = cls.make_node(
        "Squeeze", [slice_output_name + slice_suffix],
        node.outputs,
        node.name,
        axes=shrink_axis)
    return [slice_node, squeeze_node]

```
Seemed to resolve the issue for now

**Comment by hondaathma** [comment]
> I this this is related to #352 . Adding the following to strided_slice .py
> 
> ```
> 
>   @classmethod
>   def version_1(cls, node, **kwargs):
>     begin_mask = node.attr.get("begin_mask", 0)
>     end_mask = node.attr.get("end_mask", 0)
>     ellipsis_mask = node.attr.get("ellipsis_mask", 0)
>     new_axis_mask = node.attr.get("new_axis_mask", 0)
>     shrink_axis_mask = node.attr.get("shrink_axis_mask", 0)
> 
>     only_support = (int(begin_mask) is 0 and int(end_mask) is 0 and
>                     int(ellipsis_mask) is 0 and int(new_axis_mask) is 0)
>     assert only_support, "limited strided slice support"
> 
>     # Assert that strides are all ones, since we have limited support.
>     const_strides = kwargs["consts"][node.inputs[3]]
>     np.testing.assert_array_equal(np.ones_like(const_strides), const_strides)
> 
>     need_post_processing = (shrink_axis_mask > 0 or begin_mask > 0 or
>                             end_mask > 0 or ellipsis_mask > 0 or
>                             new_axis_mask > 0 or shrink_axis_mask > 0)
> 
>     slice_suffix = "_" + get_unique_suffix() if need_post_processing else ""
>     slice_output_name = node.outputs[0]
>     slice_node = cls.make_node("DynamicSlice", node.inputs[0:3],
>                                [slice_output_name + slice_suffix],
>                                node.name + slice_suffix)
> 
>     if not need_post_processing:
>       return [slice_node]
> 
>     shrink_axis = cls._int_to_set_pos_list(shrink_axis_mask)
>     squeeze_node = cls.make_node(
>         "Squeeze", [slice_output_name + slice_suffix],
>         node.outputs,
>         node.name,
>         axes=shrink_axis)
>     return [slice_node, squeeze_node]
> ```
> Seemed to resolve the issue for now
