### ISSUE TITLE
onnx-tf converter kwargs parser error

### ISSUE THREAD

**Issue by vera121** [onnx/onnx-tensorflow#349]
When I try to use the command  
**onnx-tf convert -t onnx -i mobilenet_v1_1.0_224_frozen.pb -o mobilenet_v1_1.0_224_frozen.onnx**  
The program always stops and throws the errors like this:

_INFO:root:Start converting tf pb to onnx pb:
Traceback (most recent call last):
  File "C:/Users/yche/Downloads/onnx-tensorflow/onnx_tf/cli.py", line 30, in <module>
    main()
  File "C:/Users/yche/Downloads/onnx-tensorflow/onnx_tf/cli.py", line 22, in main
    return onnx_tf.converter.main(args[1:])
  File "C:\Users\yche\Downloads\onnx-tensorflow\onnx_tf\converter.py", line 24, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "C:\Users\yche\Downloads\onnx-tensorflow\onnx_tf\converter.py", line 245, in convert
    onnx_model = frontend.tensorflow_graph_to_onnx_model(graph_def, **kwargs)
TypeError: tensorflow_graph_to_onnx_model() missing 1 required positional argument: 'output'_ 

It seems there is an input args parsing problem in your code.

**To Reproduce**
I use the python3.6.5, tensorflow is 1.8.0 and onnx is 1.3.0 on windows 10.
onnx-tf version: 1.2.1

The model is mobilenet_v1_1.0_224_frozen.pb from the [tensorflow-slim model zoo](https://github.com/tensorflow/models/tree/master/research/slim), which could be downloaded at http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz

**Comment by fumihwh** [comment]
@vera121 
You could try #350

**Comment by vera121** [comment]
Hello @fumihwh ,
After I added the 2 lines, new errors appear:
Traceback (most recent call last):
  File "C:/Users/yche/Downloads/onnx-tensorflow/onnx_tf/cli.py", line 30, in <module>
    main()
  File "C:/Users/yche/Downloads/onnx-tensorflow/onnx_tf/cli.py", line 22, in main
    return onnx_tf.converter.main(args[1:])
  File "C:\Users\yche\Downloads\onnx-tensorflow\onnx_tf\converter.py", line 24, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "C:\Users\yche\Downloads\onnx-tensorflow\onnx_tf\converter.py", line 248, in convert
    onnx_model = frontend.tensorflow_graph_to_onnx_model(graph_def, **kwargs)
  File "C:\Users\yche\Downloads\onnx-tensorflow\onnx_tf\frontend.py", line 145, in tensorflow_graph_to_onnx_model
    ignore_unimplemented, optimizer_passes)
  File "C:\Users\yche\Downloads\onnx-tensorflow\onnx_tf\frontend.py", line 158, in _make_onnx_model
    ignore_unimplemented)
  File "C:\Users\yche\Downloads\onnx-tensorflow\onnx_tf\frontend.py", line 85, in tensorflow_graph_to_onnx_graph
    onnx_graph.add_value_info_proto(node)
  File "C:\Users\yche\Downloads\onnx-tensorflow\onnx_tf\pb_wrapper.py", line 392, in add_value_info_proto
    for i, output_shape in enumerate(node.attr["_output_shapes"]):
KeyError: '_output_shapes'

**Comment by Rathna21** [comment]
Hello @fumihwh 
I also get the same error mentioned by @vera121 on adding the two lines.

**Comment by fumihwh** [comment]
@vera121 @Rathna21 
PR is updated.

**Comment by Rathna21** [comment]
Hi @fumihwh 

Error solved. Thank you 👍

**Comment by Rathna21** [comment]
@fumihwh 

The above error is solved, but I am stuck with the common error. 

**NotImplementedError: StridedSlice version 1 is not implemented.**

I get this error while converting tensorflow to ONNX both from CLI or by running the following script,
------------------------------------------------------------------
from tensorflow.core.framework import graph_pb2

from onnx_tf.frontend import tensorflow_graph_to_onnx_model
from onnx_tf.pb_wrapper import TensorflowGraph

graph_def = graph_pb2.GraphDef()
with open("frozen.pb", "rb") as f:  # load tf graph def
  graph_def.ParseFromString(f.read())
output = TensorflowGraph.get_output_node_names(
    graph_def)  # get output node names

model = tensorflow_graph_to_onnx_model(graph_def=graph_def, output=output)  # convert tf graph to onnx model
with open("output.onnx", 'wb') as f:
  f.write(model.SerializeToString())

-------------------------------------------------------------------
I installed onnx and onnx-tf from source.

while I go through the various issues, I feel many people are suffering with this problem. 
Could you please help with this problem?

**Comment by Rathna21** [comment]
@vera121 , Could you resolve Strided Slice error while converting the model ?
