### ISSUE TITLE
NotImplementedError: TruncatedNormal is not implemented

### ISSUE THREAD

**Issue by calvinlcchen** [onnx/onnx-tensorflow#357]
**Describe the bug**

I tried convert the tensorflow check points that trained according to https://github.com/lengstrom/fast-style-transfer  to ONNX.
it got the error as following
`INFO:tensorflow:Restoring parameters from fns.ckpt
INFO:tensorflow:Restoring parameters from fns.ckpt
INFO:tensorflow:Restoring parameters from fns.ckpt
INFO:tensorflow:Restoring parameters from fns.ckpt
INFO:tensorflow:Froze 146 variables.
INFO:tensorflow:Froze 146 variables.
INFO:tensorflow:Converted 146 variables to const ops.
INFO:tensorflow:Converted 146 variables to const ops.
Traceback (most recent call last):
  File "c:\users\arbula\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\arbula\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\arbula\AppData\Local\Programs\Python\Python36\Scripts\onnx-tf.exe\__main__.py", line 9, in <module>
  File "c:\users\arbula\appdata\local\programs\python\python36\lib\site-packages\onnx_tf\cli.py", line 19, in main
    return onnx_tf.converter.main(args[1:])
  File "c:\users\arbula\appdata\local\programs\python\python36\lib\site-packages\onnx_tf\converter.py", line 23, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "c:\users\arbula\appdata\local\programs\python\python36\lib\site-packages\onnx_tf\converter.py", line 229, in convert
    onnx_model = frontend.tensorflow_graph_to_onnx_model(graph_def, **kwargs)
  File "c:\users\arbula\appdata\local\programs\python\python36\lib\site-packages\onnx_tf\frontend.py", line 175, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "c:\users\arbula\appdata\local\programs\python\python36\lib\site-packages\onnx_tf\frontend.py", line 104, in tensorflow_graph_to_onnx_graph
    domain=None if node.domain in handlers else node.domain)
  File "c:\users\arbula\appdata\local\programs\python\python36\lib\site-packages\onnx_tf\common\exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "c:\users\arbula\appdata\local\programs\python\python36\lib\site-packages\onnx_tf\common\exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError: TruncatedNormal is not implemented.`

**To Reproduce**

1. train a model 
2. convert mode: onnx-tf convert -t onnx -i fns.ckpt -o starry.onnx
3. got error

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6.8
 - ONNX version: 1.2.1
 - ONNX-TF version: 1.2.1
 - Tensorflow version:  1.9.0

thanks.

**Comment by fumihwh** [comment]
@calvinlcchen 
`TruncatedNormal` is not an ONNX op.
You could convert with `ignore_unimplemented` arg.

**Comment by tjingrant** [comment]
I'd also add that, since ONNX is currently mostly for inference only, you don't usually need random ops in your ONNX graph (since you probably shouldn't need source of randomness when performing inference).

Having said that, I suggest you try to locate where random ops are used in your tf script and remove them from the inference graph when you freeze the tensorflow checkpoint. Unfortunately, tensorflow probably does not provide automatic utilities to accomplish that (although it's worth trying https://www.tensorflow.org/api_docs/python/tf/graph_util/remove_training_nodes when you freeze your graph).

**Comment by calvinlcchen** [comment]
@fumihwh 
Thanks, it's converted successful, but fail to used for WinML. 
I will further look what's wrong.
@tjingrant 
I will also try you mentioned about "remove_training_nodes", thanks.

**Comment by calvinlcchen** [comment]
close this issue due to TruncatedNormal is not an ONNX op.
