### ISSUE TITLE
Not able to convert a cuDnn LSTM Model to ONNX

### ISSUE THREAD

**Issue by sonu1-p** [onnx/onnx-tensorflow#373]
I have a tensorflow Cudnn LSTM model with following files: (I haven't built it, but I need to convert it to onnx to use it with another library)

model.ckpt-9.data-00000-of-00001	model.ckpt-9.meta
model.ckpt-9.index			checkpoint

I am trying to convert it using the below command:

onnx-tf convert -t onnx -i ./model.ckpt -o onnx_model.pb 

And I am getting this error - KeyError: "The name 'model/cudnn_lstm/opaque_kernel_saveable' refers to an Operation not in the graph."

Here is the full stack trace:

INFO:root:Start converting tf pb to onnx pb:
Traceback (most recent call last):
  File "/Users/alsuna/venv/bin/onnx-tf", line 10, in <module>
    sys.exit(main())
  File "/Users/alsuna/venv/lib/python3.6/site-packages/onnx_tf/cli.py", line 19, in main
    return onnx_tf.converter.main(args[1:])
  File "/Users/alsuna/venv/lib/python3.6/site-packages/onnx_tf/converter.py", line 23, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/Users/alsuna/venv/lib/python3.6/site-packages/onnx_tf/converter.py", line 184, in convert
    saver = tf.train.import_meta_graph(latest_ckpt + ".meta")
  File "/Users/alsuna/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1674, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/Users/alsuna/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1696, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/Users/alsuna/venv/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 852, in import_scoped_meta_graph_with_return_elements
    ops.prepend_name_scope(value, scope_to_prepend_to_names))
  File "/Users/alsuna/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/Users/alsuna/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3550, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'model/cudnn_lstm/opaque_kernel_saveable' refers to an Operation not in the graph."

I am stuck on this. I would really appreciate if anyone has suggestions on what can I try to convert this model. Please let me know if you need any more information to understand the issue.

Sorry if this is not the right place to ask this question(Since this error seems to be coming from tensorflow code), please feel free to resolve this if that is the case.

**Comment by fumihwh** [comment]
@sonu1-p Did you succeed?
