### ISSUE TITLE
Converison error : Assign is not implemented.

### ISSUE THREAD

**Issue by WilliamTambellini** [onnx/onnx-tensorflow#376]
**Describe the bug**
TF to onnx conversion error.

**To Reproduce**
install/download gpt-2 : 
https://github.com/openai/gpt-2
Try to convert models/117M/model.ckpt.data-00000-of-00001 (rename to model.ckpt)

$ onnx-tf convert -t onnx -i model.ckpt -o /tmp/gpt2.onnx
/usr/lib/python3.6/site-packages/onnx_tf/common/__init__.py:87: UserWarning: FrontendHandler.get_outputs_names is deprecated. It will be removed in future release.. Use node.outputs instead.
  warnings.warn(message)
INFO:root:Start converting tf pb to onnx pb:
INFO:tensorflow:Restoring parameters from model.ckpt
INFO:tensorflow:Restoring parameters from model.ckpt
WARNING:tensorflow:From /usr/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py:249: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
WARNING:tensorflow:From /usr/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py:249: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
INFO:tensorflow:Restoring parameters from model.ckpt
INFO:tensorflow:Restoring parameters from model.ckpt
INFO:tensorflow:Froze 148 variables.
INFO:tensorflow:Froze 148 variables.
INFO:tensorflow:Converted 148 variables to const ops.
INFO:tensorflow:Converted 148 variables to const ops.
Traceback (most recent call last):
  File "/usr/bin/onnx-tf", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/onnx_tf/cli.py", line 19, in main
    return onnx_tf.converter.main(args[1:])
  File "/usr/lib/python3.6/site-packages/onnx_tf/converter.py", line 23, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/usr/lib/python3.6/site-packages/onnx_tf/converter.py", line 229, in convert
    onnx_model = frontend.tensorflow_graph_to_onnx_model(graph_def, **kwargs)
  File "/usr/lib/python3.6/site-packages/onnx_tf/frontend.py", line 175, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/usr/lib/python3.6/site-packages/onnx_tf/frontend.py", line 104, in tensorflow_graph_to_onnx_graph
    domain=None if node.domain in handlers else node.domain)
  File "/usr/lib/python3.6/site-packages/onnx_tf/common/exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "/usr/lib/python3.6/site-packages/onnx_tf/common/exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError: Assign is not implemented.

A __self-contained__ piece of code that can demonstrate the problem is required.
$ onnx-tf convert -t onnx -i models/117M/model.ckpt -o /tmp/gpt2.onnx

**Python, ONNX, ONNX-TF, Tensorflow version**

 - Python version: 3.6
 - ONNX version: 1.4.1
 - ONNX-TF version: onnx_tf-1.2.1
 - Tensorflow version:  1.12.0

**Comment by fumihwh** [comment]
@WilliamTambellini First, Assign is not a onnx operator. This problem due to you convert from ckpt.
So I suggest you to freeze your inference pb then convert again.

**Comment by TE-WoodyLi** [comment]
@fumihwh 
I've seen the code, it seems that ckpt has been frozen before do converting. Is this part not finished? I checked the node information is strange, two input and one output for "Assing" operator. Any one knows that?

**Comment by fumihwh** [comment]
@TE-WoodyLi 
In my experience, `freeze_graph.freeze_graph` get little different graph than `tf.graph_util.convert_variables_to_constants`.
