### ISSUE TITLE
Can not convert a standard onnx model to tf model

### ISSUE THREAD

**Issue by XinyuDu** [onnx/onnx-tensorflow#377]
I'm trying to convert a onnx model to tf model. I used the command:
`onnx-tf convert -t tf -i ./resnet100.onnx -o ./output.pb`

The onnx model is downloaded from [this page](https://github.com/onnx/models/tree/master/models/face_recognition/ArcFace). The file name is resnet100.onnx.

The error information as follow:
```
(onnx2tf) root@d5b9548ceb5d:/models# onnx-tf convert -t tf -i ./resnet100.onnx -o ./output.pb
/models/onnx-tensorflow/onnx_tf/common/__init__.py:87: UserWarning: onnx_tf.common.get_outputs_names is deprecated. It will be removed in future release. Use TensorflowGraph.get_outputs_names instead.
  warnings.warn(message)
/models/onnx-tensorflow/onnx_tf/common/__init__.py:87: UserWarning: FrontendHandler.get_outputs_names is deprecated. It will be removed in future release. Use node.outputs instead.
  warnings.warn(message)
INFO:root:Start converting onnx pb to tf pb:
Traceback (most recent call last):
  File "/opt/conda/envs/onnx2tf/bin/onnx-tf", line 11, in <module>
    load_entry_point('onnx-tf', 'console_scripts', 'onnx-tf')()
  File "/models/onnx-tensorflow/onnx_tf/cli.py", line 22, in main
    return onnx_tf.converter.main(args[1:])
  File "/models/onnx-tensorflow/onnx_tf/converter.py", line 24, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/models/onnx-tensorflow/onnx_tf/converter.py", line 185, in convert
    tf_rep = backend.prepare(onnx_model, **kwargs)
  File "/models/onnx-tensorflow/onnx_tf/backend.py", line 55, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/models/onnx-tensorflow/onnx_tf/backend.py", line 75, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/models/onnx-tensorflow/onnx_tf/backend.py", line 129, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/models/onnx-tensorflow/onnx_tf/backend.py", line 224, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/models/onnx-tensorflow/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/models/onnx-tensorflow/onnx_tf/handlers/backend/sub.py", line 23, in version_7
    return [cls.make_tensor_from_onnx_node(node, **kwargs)]
  File "/models/onnx-tensorflow/onnx_tf/handlers/backend_handler.py", line 111, in make_tensor_from_onnx_node
    return cls._run_tf_func(tf_func, inputs, attrs)
  File "/models/onnx-tensorflow/onnx_tf/handlers/backend_handler.py", line 180, in _run_tf_func
    **dict([(p, attrs[p]) for p in params if p in attrs]))
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 340, in subtract
    return gen_math_ops._sub(x, y, name)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4856, in _sub
    "Sub", x=x, y=y, name=name)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 394, in _apply_op_helper
    with g.as_default(), ops.name_scope(name) as scope:
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5386, in __enter__
    return self._name_scope.__enter__()
  File "/opt/conda/envs/onnx2tf/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3813, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: '_minusscalar0' is not a valid scope name
```

Any help would be appreciated!

**Comment by fumihwh** [comment]
#348 Try this first. As error says, `_minusscalar0' is not a valid scope name`. We need to rename scope if it is invalid.

**Comment by XinyuDu** [comment]
Thanks for replaying. A new error appeared:

```
(onnx2tf) root@0d4280727026:/models# onnx-tf convert -t tf -i ./resnet100.onnx -o ./output.pb
/models/onnx-tensorflow-fix-name/onnx_tf/common/__init__.py:87: UserWarning: onnx_tf.common.get_outputs_names is deprecated. It will be removed in future release. Use TensorflowGraph.get_outputs_names instead.
  warnings.warn(message)
/models/onnx-tensorflow-fix-name/onnx_tf/common/__init__.py:87: UserWarning: FrontendHandler.get_outputs_names is deprecated. It will be removed in future release. Use node.outputs instead.
  warnings.warn(message)
INFO:root:Start converting onnx pb to tf pb:
2019-02-18 09:25:45.306379: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 64 and 112 for 'mul' (op: 'Mul') with input shapes: [64], [1,64,112,112].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/onnx2tf/bin/onnx-tf", line 11, in <module>
    load_entry_point('onnx-tf', 'console_scripts', 'onnx-tf')()
  File "/models/onnx-tensorflow-fix-name/onnx_tf/cli.py", line 22, in main
    return onnx_tf.converter.main(args[1:])
  File "/models/onnx-tensorflow-fix-name/onnx_tf/converter.py", line 24, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/models/onnx-tensorflow-fix-name/onnx_tf/converter.py", line 185, in convert
    tf_rep = backend.prepare(onnx_model, **kwargs)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 55, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 75, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 129, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 224, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/handlers/backend/p_relu.py", line 30, in version_6
    return cls._common(node, **kwargs)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/handlers/backend/p_relu.py", line 21, in _common
    neg = slope * (x - abs(x)) * 0.5
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 907, in binary_op_wrapper
    return func(x, y, name=name)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1131, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2798, in _mul
    "Mul", x=x, y=y, name=name)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3208, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 64 and 112 for 'mul' (op: 'Mul') with input shapes: [64], [1,64,112,112]
```

**Comment by fumihwh** [comment]
@XinyuDu Could you try to change `onnx-tensorflow/onnx_tf/handlers/backend/p_relu.py` L19
`slope = BroadcastMixin.explicit_broadcast([x, tensor_dict[node.inputs[1]]])`
to
`slope = BroadcastMixin.explicit_broadcast([x, tensor_dict[node.inputs[1]]], axis=1)`?

**Comment by XinyuDu** [comment]
@fumihwh Sorry for the late reply. The model  successfully converted, 'axis=1' works well. Thanks a lot for your help.

**Comment by XinyuDu** [comment]
The outputs are identical for the same input. Great work, thank you. @fumihwh

**Comment by XinyuDu** [comment]
Another error when i convert another onnx model.

```
(onnx2tf) root@cf290808cc7e:/models# onnx-tf convert -t tf -i ./mxnet_exported_arcface.onnx -o ./output.pb
/models/onnx-tensorflow-fix-name/onnx_tf/common/__init__.py:87: UserWarning: onnx_tf.common.get_outputs_names is deprecated. It will be removed in future release. Use TensorflowGraph.get_outputs_names instead.
  warnings.warn(message)
/models/onnx-tensorflow-fix-name/onnx_tf/common/__init__.py:87: UserWarning: FrontendHandler.get_outputs_names is deprecated. It will be removed in future release. Use node.outputs instead.
  warnings.warn(message)
INFO:root:Start converting onnx pb to tf pb:
Traceback (most recent call last):
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1022, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 866, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64: 'Tensor("Const:0", shape=(1,), dtype=float64)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/onnx2tf/bin/onnx-tf", line 11, in <module>
    load_entry_point('onnx-tf', 'console_scripts', 'onnx-tf')()
  File "/models/onnx-tensorflow-fix-name/onnx_tf/cli.py", line 22, in main
    return onnx_tf.converter.main(args[1:])
  File "/models/onnx-tensorflow-fix-name/onnx_tf/converter.py", line 24, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/models/onnx-tensorflow-fix-name/onnx_tf/converter.py", line 185, in convert
    tf_rep = backend.prepare(onnx_model, **kwargs)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 55, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 75, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 129, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 224, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/handlers/backend/sub.py", line 23, in version_7
    return [cls.make_tensor_from_onnx_node(node, **kwargs)]
  File "/models/onnx-tensorflow-fix-name/onnx_tf/handlers/backend_handler.py", line 111, in make_tensor_from_onnx_node
    return cls._run_tf_func(tf_func, inputs, attrs)
  File "/models/onnx-tensorflow-fix-name/onnx_tf/handlers/backend_handler.py", line 182, in _run_tf_func
    **dict([(p, attrs[p]) for p in params if p in attrs]))
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 340, in subtract
    return gen_math_ops._sub(x, y, name)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4856, in _sub
    "Sub", x=x, y=y, name=name)
  File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Sub' Op has type float64 that does not match type float32 of argument 'x'.
```

**Comment by XinyuDu** [comment]
> Another error when i convert another onnx model.
> 
> ```
> (onnx2tf) root@cf290808cc7e:/models# onnx-tf convert -t tf -i ./mxnet_exported_arcface.onnx -o ./output.pb
> /models/onnx-tensorflow-fix-name/onnx_tf/common/__init__.py:87: UserWarning: onnx_tf.common.get_outputs_names is deprecated. It will be removed in future release. Use TensorflowGraph.get_outputs_names instead.
>   warnings.warn(message)
> /models/onnx-tensorflow-fix-name/onnx_tf/common/__init__.py:87: UserWarning: FrontendHandler.get_outputs_names is deprecated. It will be removed in future release. Use node.outputs instead.
>   warnings.warn(message)
> INFO:root:Start converting onnx pb to tf pb:
> Traceback (most recent call last):
>   File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
>     preferred_dtype=default_dtype)
>   File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1022, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 866, in _TensorTensorConversionFunction
>     (dtype.name, t.dtype.name, str(t)))
> ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64: 'Tensor("Const:0", shape=(1,), dtype=float64)'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/envs/onnx2tf/bin/onnx-tf", line 11, in <module>
>     load_entry_point('onnx-tf', 'console_scripts', 'onnx-tf')()
>   File "/models/onnx-tensorflow-fix-name/onnx_tf/cli.py", line 22, in main
>     return onnx_tf.converter.main(args[1:])
>   File "/models/onnx-tensorflow-fix-name/onnx_tf/converter.py", line 24, in main
>     convert(**{k: v for k, v in vars(args).items() if v is not None})
>   File "/models/onnx-tensorflow-fix-name/onnx_tf/converter.py", line 185, in convert
>     tf_rep = backend.prepare(onnx_model, **kwargs)
>   File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 55, in prepare
>     return cls.onnx_model_to_tensorflow_rep(model, strict)
>   File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 75, in onnx_model_to_tensorflow_rep
>     return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
>   File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 129, in _onnx_graph_to_tensorflow_rep
>     onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
>   File "/models/onnx-tensorflow-fix-name/onnx_tf/backend.py", line 224, in _onnx_node_to_tensorflow_op
>     return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
>   File "/models/onnx-tensorflow-fix-name/onnx_tf/handlers/handler.py", line 60, in handle
>     return ver_handle(node, **kwargs)
>   File "/models/onnx-tensorflow-fix-name/onnx_tf/handlers/backend/sub.py", line 23, in version_7
>     return [cls.make_tensor_from_onnx_node(node, **kwargs)]
>   File "/models/onnx-tensorflow-fix-name/onnx_tf/handlers/backend_handler.py", line 111, in make_tensor_from_onnx_node
>     return cls._run_tf_func(tf_func, inputs, attrs)
>   File "/models/onnx-tensorflow-fix-name/onnx_tf/handlers/backend_handler.py", line 182, in _run_tf_func
>     **dict([(p, attrs[p]) for p in params if p in attrs]))
>   File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 340, in subtract
>     return gen_math_ops._sub(x, y, name)
>   File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4856, in _sub
>     "Sub", x=x, y=y, name=name)
>   File "/opt/conda/envs/onnx2tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
>     inferred_from[input_arg.type_attr]))
> TypeError: Input 'y' of 'Sub' Op has type float64 that does not match type float32 of argument 'x'.
> ```

mxnet caused this problem. Install mxnet by latest sources will output correct onnx model.

**Comment by duchengyao** [comment]
大佬您这个模型最后转换成功了吗？
我转完以后生成的pb tf载入不了 `INFO:tensorflow:Saver not created because there are no variables in the graph to restore`
