### ISSUE TITLE
 bad magic number in 'onnx_tf.handlers.backend.constant_like': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by vera121** [onnx/onnx-tensorflow#379]
Hi,
After installing the converter using "pip install -e ." on the Ubuntu 16.04 with the latest master branch (ef8bea96297bfd8fe51ca4e891b887741b5fad40)
An error shows up when I try to use 
onnx-tf -h

/home/yche/onnx-tensorflow/onnx_tf/common/__init__.py:87: UserWarning: onnx_tf.common.get_outputs_names is deprecated. It will be removed in future release. Use TensorflowGraph.get_outputs_names instead.
  warnings.warn(message)
Traceback (most recent call last):
  File "/home/yche/anaconda2/envs/python3/bin/onnx-tf", line 11, in <module>
    load_entry_point('onnx-tf', 'console_scripts', 'onnx-tf')()
  File "/home/yche/anaconda2/envs/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/yche/anaconda2/envs/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/yche/anaconda2/envs/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/yche/anaconda2/envs/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/yche/onnx-tensorflow/onnx_tf/__init__.py", line 1, in <module>
    from . import frontend
  File "/home/yche/onnx-tensorflow/onnx_tf/frontend.py", line 16, in <module>
    from onnx_tf.common.handler_helper import get_all_frontend_handlers
  File "/home/yche/onnx-tensorflow/onnx_tf/common/handler_helper.py", line 5, in <module>
    from onnx_tf.handlers.backend import *  # noqa
ImportError: bad magic number in 'onnx_tf.handlers.backend.constant_like': b'\x03\xf3\r\n'

TensorFlow: 1.8.0
python: 3.6.8
onnx: 1.3.0
onnx-tf: 1.2.1

**Comment by fumihwh** [comment]
@vera121 Do you have untracked local file? Try `git clean -xdf` then install again.

**Comment by vera121** [comment]
> @vera121 Do you have untracked local file? Try `git clean -xdf` then install again.

Thanks. The error is gone after that.
