### ISSUE TITLE
NotImplementedError: ATen is not implemented.

### ISSUE THREAD

**Issue by NoushNabi** [onnx/onnx-tensorflow#393]
**Describe the bug**

I got an error when converting an ONNX model to TensorFlow.

**To Reproduce**

- Using pyTorch-nightly-cpu, I have converted the PyTorch model of the [AtlasNet](https://github.com/ThibaultGROUEIX/AtlasNet) to ONNX model using:
`torch.onnx.export(network, input_var, "atlasNet.onnx")`
        
- Loaded the ONNX model and verified it:
`model = onnx.load("atlasNet.onnx")`
`onnx.checker.check_model(model)`

- Imported the ONNX model to Tensorflow
`tf_rep = prepare(model)`

I get this error in this step:

> Traceback (most recent call last):
>   File "onnx2tf.py", line 13, in <module>
>     tf_rep = prepare(model)
>   File ".../onnx-tensorflow/onnx_tf/backend.py", line 55, in prepare
>     return cls.onnx_model_to_tensorflow_rep(model, strict)
>   File ".../onnx-tensorflow/onnx_tf/backend.py", line 75, in onnx_model_to_tensorflow_rep
>     return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
>   File ".../onnx-tensorflow/onnx_tf/backend.py", line 129, in _onnx_graph_to_tensorflow_rep
>     onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
>   File ".../onnx-tensorflow/onnx_tf/backend.py", line 226, in _onnx_node_to_tensorflow_op
>     exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type)
>   File ".../onnx-tensorflow/onnx_tf/common/exception.py", line 31, in __call__
>     super(OpUnimplementedException, self).__call__(op, version, domain)
>   File ".../onnx-tensorflow/onnx_tf/common/exception.py", line 13, in __call__
>     raise self._func(self.get_message(*args, **kwargs))
> **NotImplementedError: ATen is not implemented.**
> 

**ONNX model file**
The model can be downloaded from here:
https://drive.google.com/file/d/1nL6iaVjDea_JDA4tUJahcPmwvykh-B1o/view?usp=sharing

**Python, ONNX, ONNX-TF, Tensorflow version**
 - Python version: 3.6
 - ONNX version: built from source: [fdb978a58](https://github.com/onnx/onnx/tree/fdb978a580bcb461ea077b9772c973928b8dbf5f)
 - ONNX-TF version: built from source: [b4b0fafbd](https://github.com/onnx/onnx-tensorflow/tree/b4b0fafbd653e1c2fafa688a92a35ba427347fe8)
 - Tensorflow version: 1.13.1

**Comment by chinhuang007** [comment]
We don't have support for ATen because it seems a special case for Caffe2 to allow for quick prototyping, https://github.com/onnx/onnx/blob/master/docs/Operators.md#ATen. Plus it is one of the experimental ops that are not required to be supported by converters. The concept of "experimental ops" is going away in onnx next release 1.5. And for all the existing experimental ops, they'll be either, 1) promoted to ONNX standard op set if useful, or 2) removed, commented at the end of https://github.com/onnx/onnx/issues/1756. So we will look into the details in onnx 1.5 to decide  whether and how to support it.

**Comment by ajaysg** [comment]
My onnx model graph has ATen operator. when i try to convert that to tensorrt it throws an error like
No importer registered for op: ATen
what is the solution?

**Comment by chinhuang007** [comment]
The error seems coming from tensorrt, not onnx-tf. Since ATen is still not in the latest onnx master, we have no plans to support it as now. If you want to converter the old version of onnx file to tensorrt, I would suggest check with the tensorrt community to see if they would support this experimental op.

**Comment by ajaysg** [comment]
@chinhuang007 thank you for the clarification

**Comment by rishabh-ojha98** [comment]
@NoushNabi Check your onnx and torch version. It should be:

onnx == 1.6.0
onnx-tf==1.5.0
torch == 1.4.0

It worked for me. Thanks

**Comment by thomas-beznik** [comment]
Hello,
I am also running into the same error... Is there a way to overcome it? I believe that it must be caused by the operation "F.interpolate" from torch.nn.functional. Is there any way to use another equivalent operation that doesn't use ATen? Any direction on how to solve this would be great!

**Comment by MasKong** [comment]
I also had the same error. 
There are a lot of operator in pytorch is implemented in ATen which is not included in tensorflow. Therefore the solution is to reimplement the operator in pure pytorch.

For example, cosine_similarity in pytorch is implemented in ATen and caused this error when I converted onnx to tf. Then I reimplement consine_similarity function and it works.

Hope this could help you, thanks!

**Comment by Shiro-LK** [comment]
I have exactly the same error message about : "NotImplementedError: ATen is not implemented." with an huggingface model. Does anyone succeed to convert a pytorch transformer model into TF ?
