### ISSUE TITLE
Clip operator run_node error

### ISSUE THREAD

**Issue by colinback** [onnx/onnx-tensorflow#397]
**Describe the bug**

```python
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    y = run_node(node, [x])["y"]
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/backend.py", line 174, in run_node
    ops = cls._onnx_node_to_tensorflow_op(node, input_dict)
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/backend.py", line 225, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/handlers/backend/clip.py", line 30, in version_6
    return cls._common(node, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/handlers/backend/clip.py", line 21, in _common
    node, inputs=[x, clip_value_min, clip_value_max])
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/handlers/backend_handler.py", line 111, in make_tensor_from_onnx_node
    return cls._run_tf_func(tf_func, inputs, attrs)
  File "/usr/local/lib/python2.7/dist-packages/onnx_tf/handlers/backend_handler.py", line 174, in _run_tf_func
    params = tf_func.__closure__[1].cell_contents.args
AttributeError: 'function' object has no attribute 'args'
```

**To Reproduce**

```python
import onnx
import numpy as np
from onnx_tf.backend import run_node
from onnx import helper

node = onnx.helper.make_node('Clip', inputs=['x'], outputs=['y'], min=-1.0, max=1.0)
shape = [10, 10]
x = np.ones(shape).astype(np.float32).reshape(shape)
y = run_node(node, [x])["y"]
```

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
- Python version:
2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0]
- ONNX version:
1.4.1
- ONNX-TF version:
1.2.1
- Tensorflow version:
1.13.1

**Comment by colinback** [comment]
The error is gone after I install latest onnx-tf using `pip install onnx-tf .` follwing README.txt
