### ISSUE TITLE
onnx cannot import prepare

### ISSUE THREAD

**Issue by KKSMahesvara** [onnx/onnx-tensorflow#402]
I tried to download onnx using 
conda install -c conda-forge protobuf numpy
pip install onnx

and I got the following errors when running onnx to tensorflow file in examples.
Traceback (most recent call last):
  File "C:/Users/donov/Anaconda3/envs/VRenv2P37/onnx-tensorflow/example/onnx_to_tf.py", line 3, in <module>
    from onnx.backend import prepare
ImportError: cannot import name 'prepare'

How do I resolve this? Or did I not do an extra step?

Python 3.6
Onnx 1.4.1

My goal is to convert onnx(from Matlab) to tf that has batchNormalization, because onnx_tf cannot convert it, due to this error.
==> Context: Bad node spec: input: "conv_1" input: "batchnorm_1_scale" input: "batchnorm_1_B" input: "batchnorm_1_mean" input: "batchnorm_1_var" output: "batchnorm_1" name: "batchnorm_1" op_type: "BatchNormalization" attribute { name: "epsilon" f: 1e-05 type: FLOAT } attribute { name: "is_test" i: 1 type: INT } attribute { name: "consumed_inputs" ints: 0 ints: 0 ints: 0 ints: 1 ints: 1 type: INTS }

**Comment by chinhuang007** [comment]
@KKSMahesvara Can you please provide the onnx file?

**Comment by KKSMahesvara** [comment]
[AiSweetB3.zip](https://github.com/onnx/onnx-tensorflow/files/3036371/AiSweetB3.zip)
Here it is.
I had to zip it to upload it it here, I don't know if zipping it will cause any data loss.

**Comment by chinhuang007** [comment]
The problem is in the onnx file. The opset version is 6 but BatchNormalization has an unsupported attribute "consumed_inputs" (was in opset=1, removed in opset=6). Is the onnx file exported from some framework?

Basically the onnx file did not pass the onnx checker.
Traceback (most recent call last):
  File "import_ai_sweetb.py", line 10, in <module>
    tf_rep = prepare(model)
  File "/home/chinhuang/onnx-tensorflow/onnx_tf/backend.py", line 54, in prepare
    super(TensorflowBackend, cls).prepare(model, device, **kwargs)
  File "/home/chinhuang/venv_py3/lib/python3.6/site-packages/onnx-1.4.1-py3.6-linux-x86_64.egg/onnx/backend/base.py", line 74, in prepare
    onnx.checker.check_model(model)
  File "/home/chinhuang/venv_py3/lib/python3.6/site-packages/onnx-1.4.1-py3.6-linux-x86_64.egg/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: consumed_inputs for operator BatchNormalization

**Comment by KKSMahesvara** [comment]
The onnx file is exported from MATLAB R2018a via 'exportONNXNetwork' provided by my organization.
https://www.mathworks.com/help/deeplearning/ref/exportonnxnetwork.html

Which means I don't have alternatives if I use that version of Matlab with BatchNormalization?
Also, do you know if Matlab removed it in their newer release?

Thank you.
