### ISSUE TITLE
Cannot convert emotion_ferplus to TF

### ISSUE THREAD

**Issue by qcoh** [onnx/onnx-tensorflow#412]
**Describe the bug**

When I try to convert the onnx model [emotion_ferplus](https://github.com/onnx/models/tree/master/emotion_ferplus) to TensorFlow, I get an error.

Shortened, presumably relevant, error message:
```
[...]
Traceback (most recent call last):
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 3 from 1 for 'convolution_8' (op: 'Conv2D') with input shapes: [1,1,1,256], [3,3,256,256].

During handling of the above exception, another exception occurred:
[...]
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Negative dimension size caused by subtracting 3 from 1 for 'convolution_8' (op: 'Conv2D') with input shapes: [1,1,1,256], [3,3,256,256].
```

Full error message:
```
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/jerry/.local/lib/python3.6/site-packages/onnx_tf/handlers/backend/reshape.py:31: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From /home/jerry/.local/lib/python3.6/site-packages/onnx_tf/handlers/backend_handler.py:180: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
2019-04-28 18:33:13.686603: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-28 18:33:13.739377: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2019-04-28 18:33:13.747111: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x6d91590 executing computations on platform Host. Devices:
2019-04-28 18:33:13.748043: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 3 from 1 for 'convolution_8' (op: 'Conv2D') with input shapes: [1,1,1,256], [3,3,256,256].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./onnx2tf.py", line 17, in <module>
    output = prepare(onnx_model)
  File "/home/jerry/.local/lib/python3.6/site-packages/onnx_tf/backend.py", line 55, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/jerry/.local/lib/python3.6/site-packages/onnx_tf/backend.py", line 75, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/jerry/.local/lib/python3.6/site-packages/onnx_tf/backend.py", line 129, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/home/jerry/.local/lib/python3.6/site-packages/onnx_tf/backend.py", line 224, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/home/jerry/.local/lib/python3.6/site-packages/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/home/jerry/.local/lib/python3.6/site-packages/onnx_tf/handlers/backend/conv.py", line 11, in version_1
    return cls.conv(node, kwargs["tensor_dict"])
  File "/home/jerry/.local/lib/python3.6/site-packages/onnx_tf/handlers/backend/conv_mixin.py", line 150, in conv
    for (x, weight) in zip(xs, weight_groups)
  File "/home/jerry/.local/lib/python3.6/site-packages/onnx_tf/handlers/backend/conv_mixin.py", line 150, in <listcomp>
    for (x, weight) in zip(xs, weight_groups)
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 851, in convolution
    return op(input, filter)
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 591, in __call__
    return self.call(inp, filter)
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 208, in __call__
    name=self.name)
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/home/jerry/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Negative dimension size caused by subtracting 3 from 1 for 'convolution_8' (op: 'Conv2D') with input shapes: [1,1,1,256], [3,3,256,256].
```

**To Reproduce**

* Download "Opset 2" version of [emotion_ferplus](https://github.com/onnx/models/tree/master/emotion_ferplus)
* Extract file
* Run
```python
import onnx
from onnx_tf.backend import prepare

onnx_model = onnx.load("emotion_ferplus/model.onnx")
output = prepare(onnx_model)
# model export omitted since the issue occurs in prepare
```

**ONNX model file**

[emotion_ferplus, opset version 2](https://onnxzoo.blob.core.windows.net/models/opset_2/emotion_ferplus/emotion_ferplus.tar.gz) (31 MB)

**Python, ONNX, ONNX-TF, Tensorflow version**

 - Python version: 3.6.7
 - ONNX version: 1.5.0
 - ONNX-TF version: 1.2.1
 - Tensorflow version: 1.13.1

**Additional context**

Using the debugger, I found that the problem occurs with "Convolution901", which has the inputs "ReLU887_Output_0" and "Parameter675". 

When inspecting the state at https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/backend.py#L129, I see that the dimensions of "ReLU887_Output_0" are `1, 256, 1, 1` and `256, 256, 3, 3` for "Parameter675".

When I load the model in [Netron](https://github.com/lutzroeder/netron), the dimensions of "ReLU887_Output_0" are `1, 256, 8, 8`.

**Comment by Niz13** [comment]
Hello,
I'm facing the same issue.
Did you manage to solve it?

Thank you!

**Comment by qcoh** [comment]
Unfortunately, I didn't have time to investigate further. I will get back to you if I figure something out.

**Comment by qcoh** [comment]
Ok, I think the problem is due to padding. First of all, the issue occurs with every convolution in this network, e.g. the output of `Convolution771` should have the shape `1,128,32,32` but actually has the shape `1,128,26,26`.

I stepped through the relevant code and found that in https://github.com/onnx/onnx-tensorflow/blob/ef6ee95dd04c314c4888444168b80e682c9938db/onnx_tf/handlers/backend/conv_mixin.py#L143-L149, the output of `tf.nn.convolution` has incorrect shape for the first time. Note that padding is always set to "VALID" here.

According to Netron, every convolution in emotion_ferplus has padding set to "SAME_UPPER".
