### ISSUE TITLE
RNN models converted by keras-onnx failed to run with backend

### ISSUE THREAD

**Issue by fjfjfan** [onnx/onnx-tensorflow#441]
**Describe the bug**
I used the keras-onnx code in master branch to generate a RNN onnx model, but failed to use it in onnx_tf backend.prepare(), 

```
model=onnx.load("keras_rnn.onnx")
tf_rep = onnx_tf.backend.prepare(model)
```
I will get error as below:
```
tf_rep = onnx_tf.backend.prepare(model)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/fjbnu/Downloads/onnx-tensorflow/onnx_tf/backend.py", line 63, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/Users/fjbnu/Downloads/onnx-tensorflow/onnx_tf/backend.py", line 83, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/Users/fjbnu/Downloads/onnx-tensorflow/onnx_tf/backend.py", line 137, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/Users/fjbnu/Downloads/onnx-tensorflow/onnx_tf/backend.py", line 232, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/Users/fjbnu/Downloads/onnx-tensorflow/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/Users/fjbnu/Downloads/onnx-tensorflow/onnx_tf/handlers/backend/rnn.py", line 157, in version_7
    return cls._common(node, **kwargs)
  File "/Users/fjbnu/Downloads/onnx-tensorflow/onnx_tf/handlers/backend/rnn.py", line 131, in _common
    rnn_kwargs, tf_activations, direction)
  File "/Users/fjbnu/Downloads/onnx-tensorflow/onnx_tf/handlers/backend/rnn_mixin.py", line 38, in rnn
    outputs, states = tf.nn.dynamic_rnn(cell_fw, x, **rnn_kwargs)
  File "/Users/fjbnu/anaconda2/envs/python3.6/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 631, in dynamic_rnn
    dtype=dtype)
  File "/Users/fjbnu/anaconda2/envs/python3.6/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 701, in _dynamic_rnn_loop
    "Input size (depth of inputs) must be accessible via shape inference,"
ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None.
```

**To Reproduce**
To generate the model:
```
# -*- coding: utf-8 -*-
import time
import math
import numpy as np
from keras.models import Sequential
from keras.layers import SimpleRNN, GRU, LSTM
from sklearn.metrics import mean_squared_error
from keras import backend as K
import tensorflow as tf
import keras2onnx

# Fix random seed for reproducibility
np.random.seed(1)

data_dim = 4  # input_size
timesteps = 3  # seq_length

# expected input data shape: (batch_size, timesteps, data_dim)
test_input = np.random.random_sample((100, timesteps, data_dim))
test_output = np.random.random_sample((100, 128))

# Number of layer and number of neurons in each layer
num_neur = [128, 256, 128]
# Training times
epochs = 200
# Batch size
batch_size = 50

# Record time
start_cr_a_fit_net = time.time()
# Create and fit the RNN network
model = Sequential()

for i in range(len(num_neur)):  # multi-layer
    if len(num_neur) == 1:
        model.add(SimpleRNN(num_neur[i], input_shape=(timesteps, data_dim), unroll=True))
    else:
        if i < len(num_neur) - 1:
            model.add(SimpleRNN(num_neur[i], input_shape=(timesteps, data_dim), return_sequences=True, unroll=True))
        else:
            model.add(SimpleRNN(num_neur[i], input_shape=(timesteps, data_dim), unroll=True))

# Summary the structure of neural network
model.summary()
# Compile the neural network
model.compile(loss='mean_squared_error', optimizer='adam')
# Fit the LSTM network
model.fit(test_input, test_output, epochs=epochs, batch_size=batch_size, verbose=0)
end_cr_a_fit_net = time.time() - start_cr_a_fit_net
print('Running time of creating and fitting the LSTM network: %.2f Seconds' % (end_cr_a_fit_net))
print('model.inputs', model.inputs)
print('model.outputs', model.outputs)
test_input = np.random.random_sample((1, timesteps, data_dim)).astype(np.float32)
test_output = model.predict(test_input)
onnx_model = keras2onnx.convert_keras(model, model.name)

import onnx
onnx_filename = "keras_rnn1.onnx"
onnx.save_model(onnx_model, onnx_filename)
K.clear_session()
```

**ONNX model file**
[keras_rnn.onnx.zip](https://github.com/onnx/onnx-tensorflow/files/3300568/keras_rnn.onnx.zip)

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
Python version:
2.7.15 (default, Jan 23 2019, 13:23:13)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
ONNX version:
1.5.0
ONNX-TF version:
1.2.1
Tensorflow version:
1.13.1

**Additional context**

**Comment by sonu1-p** [comment]
One thing I have noted while using the keras-onnx converter is that it does not add the initializers as "inputs" in the generated onnx model(this was true when I was using the converter some weeks ago). The onnx shape inference relies on this that all initializers must be present as inputs to the onnx model and fails to deduce shapes. That might be causing this problem for you. Check once if the initializers are present as input in your model. If not, try adding them and then run shape inference and see if shapes are being inferred correctly. Please ignore if this is not the case with your model!

**Comment by chinhuang007** [comment]
Your error seems coming from python 3.6 but get_version.py returns python 2.7. I just tested your code and it works okay.
Using TensorFlow backend.
WARNING:tensorflow:From /home/chinhuang/venv_py3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
simple_rnn_1 (SimpleRNN)     (None, 3, 128)            17024
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (None, 3, 256)            98560
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 128)               49280
=================================================================
Total params: 164,864
Trainable params: 164,864
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:From /home/chinhuang/venv_py3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-06-19 01:03:17.216395: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-19 01:03:17.222441: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100060000 Hz
2019-06-19 01:03:17.223101: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2590c60 executing computations on platform Host. Devices:
2019-06-19 01:03:17.223133: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Running time of creating and fitting the LSTM network: 3.53 Seconds
model.inputs [<tf.Tensor 'simple_rnn_1_input:0' shape=(?, 3, 4) dtype=float32>]
model.outputs [<tf.Tensor 'simple_rnn_3/Tanh_2:0' shape=(?, 128) dtype=float32>]

My env is:
Python version:
3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]
ONNX version:
1.5.0
ONNX-TF version:
1.2.1
Tensorflow version:
1.13.1

**Comment by fjfjfan** [comment]
@chinhuang007 Thanks for the prompt response, yes, I got the error from python 2.7 with some other customized code firstly, so I reproduced it in python 3.6 then, sorry for the misunderstanding.

**Comment by fjfjfan** [comment]
@sonu1-p Thanks for the info! Also thank you for the fix for keras-onnx lstm several days ago :-)  yes, the old models converted by keras-onnx some days ago could work with onnx-tf. Could you please talk more about how to "Check once if the initializers are present as input in your model. If not, try adding them and then run shape inference and see if shapes are being inferred correctly. "?  Is it a bug of keras-onnx? Thanks a lot!

**Comment by sonu1-p** [comment]
@fjfjfan Thanks! :) Yes, I think it is a bug if the behavior is not fixed yet. When trying to run ONNX shape inference with a LSTM model converted using keras-onnx shape inference was failing(I don't remember exact op for which it was). The reason for that was some ONNX shape inference functions were assuming that there will be a "input" (Which according to ONNX ir.md is ValueInfo containing the input “parameters” of the graph, possibly initialized by a default value found in ‘initializer.’ ) for each initializer and their code is written accordingly.

**Comment by chinhuang007** [comment]
The problem seems coming from Reshape, taking inputs of data 'rnn_y_permuted': <tf.Tensor 'Transpose1:0' shape=(?, 6, 1, 128) dtype=float32> and 'shape_tensor': <tf.Tensor 'Const_3:0' shape=(3,) dtype=int64> with [-1, 6, 128] and producing output 'simple_rnn_1_transpose_1_0': <tf.Tensor 'Reshape:0' shape=(?, ?, ?) dtype=float32>. This data will cause tf.nn.dynamic_rnn to fail. I think the solution might be in the keras converter.

**Comment by fjfjfan** [comment]
@chinhuang007 Thanks a lot! I will open a keras-onnx issue then, thanks!
