### ISSUE TITLE
Convert onnx to tensorflow

### ISSUE THREAD

**Issue by TTMRonald** [onnx/onnx-tensorflow#442]
I have no errors when I convert pytorch to onnx. But I meet an error when I converted onnx to tensorflow.

My code is
`onnx-tf convert -t tf -i convert_models/best_model.onnx -o convert_models/best_model.pb`
My error is

> Traceback (most recent call last):
  File "/Users/ronald/anaconda2/bin/onnx-tf", line 7, in <module>
    from onnx_tf.cli import main
  File "/Users/ronald/anaconda2/lib/python2.7/site-packages/onnx_tf/__init__.py", line 1, in <module>
    from . import frontend
  File "/Users/home/anaconda2/lib/python2.7/site-packages/onnx_tf/frontend.py", line 16, in <module>
    from onnx_tf.common.handler_helper import get_all_frontend_handlers
  File "/Users/home/anaconda2/lib/python2.7/site-packages/onnx_tf/common/handler_helper.py", line 5, in <module>
    from onnx_tf.handlers.backend import *  # noqa
  File "/Users/home/anaconda2/lib/python2.7/site-packages/onnx_tf/handlers/backend/is_inf.py", line 8, in <module>
    @tf_func(tf.math.is_inf)
AttributeError: 'module' object has no attribute 'is_inf'

But I print the tensorflow version in onnx_tf/handlers/backend/is_inf.py. I find the tensorflow version is 1.11.0 which is inconsistent with the version I am using.

How can I solve this problem? Thanks.

 - Python version: 3.5.6
 - PyTorch version: 1.2.0a0+4fee532 (install master branch from source)
 - ONNX version: 1.1.2
 - ONNX-TF version: 1.2.1 (install master branch from source)
 - Tensorflow version: 1.13.1

**Comment by 363325971** [comment]
same problem, have you fixed it??

**Comment by ABlueLight** [comment]
@363325971  i solve this by update tensorflow to 1.14.0. but i don't why ....

**Comment by wyf94** [comment]
go to this files "/Users/home/anaconda2/lib/python2.7/site-packages/onnx_tf/handlers/backend/is_inf.py"  
change "@tf_func(tf.math.is_inf)" to " @tf_func(tf.is_inf) "
