### ISSUE TITLE
Can not import `onnx_tf`

### ISSUE THREAD

**Issue by dnnagy** [onnx/onnx-tensorflow#458]
Can not import `onnx_tf`
 
 - Python version: Python 3.6.7 :: Anaconda, Inc.
 - ONNX version: 1.5.0
 - ONNX-TF version: 1.3.0
 - Tensorflow version:  1.13.1

Code:
```
>>> import onnx_tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nagydaniel/Documents/Munka/asseco/ml/notebooks/onnx-tensorflow/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/Users/nagydaniel/Documents/Munka/asseco/ml/notebooks/onnx-tensorflow/onnx_tf/backend.py", line 21, in <module>
    import tensorflow as tf
  File "/Users/nagydaniel/miniconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/Users/nagydaniel/miniconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/Users/nagydaniel/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 30, in <module>
    from tensorflow.python.framework.sparse_tensor import SparseTensor
  File "/Users/nagydaniel/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/sparse_tensor.py", line 26, in <module>
    from tensorflow.python.framework import tensor_util
  File "/Users/nagydaniel/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 32, in <module>
    from tensorflow.python.framework import fast_tensor_util
  File "__init__.pxd", line 872, in init tensorflow.python.framework.fast_tensor_util
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```

**Comment by fumihwh** [comment]
@dnnagy Try reinstall numpy.

**Comment by namnh2204** [comment]
I have the same issue. Reinstall numpy did not work.

**Comment by DiegoMartinezGlez** [comment]
neither for me
