### ISSUE TITLE
NotImplementedError: Split version 11 is not implemented.

### ISSUE THREAD

**Issue by ningningG** [onnx/onnx-tensorflow#516]
Platform (like ubuntu 16.04/win10):
win10
Python version:
3.7.4
Tensorflow version:
Tensorflow 1.14.0 with GPU

There is  an NotImplementedError when converte  onnx_node to tensorflow_op:

```
Traceback (most recent call last):
  File "D:/mx2tf_CT/mx2tf/onnx2tf1.py", line 6, in <module>
    tf_rep = prepare(onnx_model)  # prepare tf representation
  File "C:\Users\Administrator\AppData\Local\Continuum\anaconda3\envs\model_convertor\lib\site-packages\onnx_tf\backend.py", line 55, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "C:\Users\Administrator\AppData\Local\Continuum\anaconda3\envs\model_convertor\lib\site-packages\onnx_tf\backend.py", line 75, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "C:\Users\Administrator\AppData\Local\Continuum\anaconda3\envs\model_convertor\lib\site-packages\onnx_tf\backend.py", line 129, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "C:\Users\Administrator\AppData\Local\Continuum\anaconda3\envs\model_convertor\lib\site-packages\onnx_tf\backend.py", line 226, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "C:\Users\Administrator\AppData\Local\Continuum\anaconda3\envs\model_convertor\lib\site-packages\onnx_tf\handlers\handler.py", line 63, in handle
    exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type, cls.SINCE_VERSION)
  File "C:\Users\Administrator\AppData\Local\Continuum\anaconda3\envs\model_convertor\lib\site-packages\onnx_tf\common\exception.py", line 34, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "C:\Users\Administrator\AppData\Local\Continuum\anaconda3\envs\model_convertor\lib\site-packages\onnx_tf\common\exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError: Split version 11 is not implemented.
```

Why this error occured? How to solve it? Any ideas?

**Comment by chinhuang007** [comment]
Thanks for reporting the issue. ONNX has an update for Split in opset 11. We are working on a solution.

**Comment by chinhuang007** [comment]
We are working on the new and updated ops introduced in ONNX 1.6 (opset 11) and will track the progress in this issue, #449. Will give Split a high priority.

**Comment by Ehtasha** [comment]
@chinhuang007 

My onnx version is 1.6.0 but still I'm getting an error of 'version 11 is not implemented'

**Comment by chinhuang007** [comment]
@Ehtasha please build from source using the master branch if you have tensorflow 2.0 or the tf-1.x branch for tf 1.x. The pip install is still at the opset 10 level and will be refreshed only after we complete the onnx-tf 1.6 release.

**Comment by Ehtasha** [comment]
@chinhuang007  Thanks for your quick response.

Can you please give your precious 5 minutes on this issue https://github.com/onnx/onnx-tensorflow/issues/550 which I have created on onnx-tensorflow repository.

**Comment by chinhuang007** [comment]
Close since both branches are updated.
