### ISSUE TITLE
version = opset_dict[domain]

### ISSUE THREAD

**Issue by Zhang-Nian** [onnx/onnx-tensorflow#562]
onnx : 1.5.0
tensorflow: 2.1.0
tensorflow-additions:0.8.1
python: 3.6

command:  git clone https://github.com/onnx/onnx-tensorflow.git && cd onnx-tensorflow && pip install -e .

Installing collected packages: onnx-tf
  Attempting uninstall: onnx-tf
    Found existing installation: onnx-tf 1.5.0
    Uninstalling onnx-tf-1.5.0:
      Successfully uninstalled onnx-tf-1.5.0
  Running setup.py develop for onnx-tf
Successfully installed onnx-tf

there are some error? 

python code :  

`import onnx
import numpy as np
from onnx_tf.backend import prepare

model = onnx.load("./text.onnx")
tf_rep = prepare(model)

img = np.load("./assets/image.npz")
output = tf_rep.run(img.reshape([1, 1,28,28]))

print("outpu mat: \n",output)
print("The digit is classified as ", np.argmax(output))

import tensorflow as tf
with tf.Session() as persisted_sess:
    print("load graph")
    persisted_sess.graph.as_default()
    tf.import_graph_def(tf_rep.predict_net.graph.as_graph_def(), name='')
    inp = persisted_sess.graph.get_tensor_by_name(
        tf_rep.predict_net.tensor_dict[tf_rep.predict_net.external_input[0]].name
    )
    out = persisted_sess.graph.get_tensor_by_name(
        tf_rep.predict_net.tensor_dict[tf_rep.predict_net.external_output[0]].name
    )
    res = persisted_sess.run(out, {inp: img.reshape([1, 1,28,28])})
    print(res)
    print("The digit is classified as ",np.argmax(res))

tf_rep.export_graph('tf.pb')`

error: 
Traceback (most recent call last):
  File "convert.py", line 7, in <module>
    tf_rep = prepare(model)
  File "/data/ToTensorflow/onnx-tensorflow/onnx_tf/backend.py", line 65, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/data/Tensorflow/onnx-tensorflow/onnx_tf/backend.py", line 85, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/data/ToTensorflow/onnx-tensorflow/onnx_tf/backend.py", line 97, in _onnx_graph_to_tensorflow_rep
    handlers = cls._get_handlers(opset)
  File "/data/ToTensorflow/onnx-tensorflow/onnx_tf/backend.py", line 252, in _get_handlers
    return get_all_backend_handlers(opset_dict)
  File "/data/ToTensorflow/onnx-tensorflow/onnx_tf/common/handler_helper.py", line 21, in get_all_backend_handlers
    version = opset_dict[domain]
KeyError: ''

how to fix it ?   thank you

**Comment by chinhuang007** [comment]
Is it possible to share text.onnx and image.npz so I could reproduce and look into the error?
