### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'Tensor'

### ISSUE THREAD

**Issue by cannguyen275** [onnx/onnx-tensorflow#583]
**Describe the bug**
I convert Pytorch model to Tensorflow by using onnx.
Geting this error when trying to convert onnx to tensorflow model.
The code is:
```python
from onnx_tf.backend import prepare
output_onnx = 'myONNXmodel.onnx'
input_names = ["input0"]
output_names = ["output"]
inputs = torch.randn(1, 3, 600, 600)
torch_out = torch.onnx._export(net,
                            inputs,
                            output_onnx,
                            verbose=True,
                            input_names=input_names,
                            output_names=output_names,
                            example_outputs=True,  # to show sample output dimension
                            kThis section can be obtained by running `get_version.py` from util folder.eep_initializers_as_inputs=True, 
                            dynamic_axes={
                                  "input0": [2, 3],  #to make dynamic axes for width, height
                                   "output": [1, 2],
                              })
model = onnx.load('mymodel.onnx')
tf_rep = prepare(model)
tf_rep.export_graph("myTensorflowModel.pb")
```
The bug is:
```bash
Traceback (most recent call last):
  File "/home/can/onnx2tf.py",This section can be obtained by running `get_version.py` from util folder. line 28, in <module>
    tf_rep = prepare(model)  # Import the ONNX model to Tensorflow
  File "/home/can/miniconda3/envs/env1/lib/python3.6/site-packages/onnx_tf/backend.py", line 65, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/can/miniconda3/envs/env1/lib/python3.6/site-packages/onnx_tf/backend.py", line 85, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/can/miniconda3/envs/env1/lib/python3.6/site-packages/onnx_tf/backend.py", line 143, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/home/can/miniconda3/envs/env1/lib/python3.6/site-packages/onnx_tf/backend.py", line 239, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/home/can/miniconda3/envs/env1/lib/python3.6/site-packages/onnx_tf/handlers/handler.py", line 61, in handle
    return ver_handle(node, **kwargs)
  File "/home/can/miniconda3/envs/env1/lib/python3.6/site-packages/onnx_tf/handlers/backend/upsample.py", line 68, in version_9
    new_h_w_shape = tf.cast(h_w_scale * h_w_shape, tf.int32)
TypeError: can't multiply sequence by non-int of type 'Tensor'
```

**Python, ONNX, ONNX-TF, Tensorflow version**
 - Python version: 3.6
 - ONNX version: 1.6
 - ONNX-TF version:1.5
 - Tensorflow version: 1.12

Hope to get your advance to solve it!
Thanks

**Comment by buildist** [comment]
Had the same problem, I fixed it by setting opset_version=10 in onnx.export()

**Comment by chinhuang007** [comment]
@cannguyen275 Is it possible to share your onnx file for debugging?

**Comment by cannguyen275** [comment]
@chinhuang007 I've fixed it by removing the dynamic axes parameters. I check the code and found out that it need to have the value of input size.
