### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.api._v1.keras.utils' has no attribute 'register_keras_serializable'

### ISSUE THREAD

**Issue by Tian14267** [onnx/onnx-tensorflow#689]
**Describe the bug**

Traceback (most recent call last):
  File "/home/fffan/fffan_files/Experiment/Example/onnx2pb/ommx2pb.py", line 2, in <module>
    from onnx_tf.backend import prepare
  File "/home/fffan/下载/onnx-tensorflow-rel-1.6.0/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/home/fffan/下载/onnx-tensorflow-rel-1.6.0/onnx_tf/backend.py", line 29, in <module>
    from onnx_tf.common.handler_helper import get_all_backend_handlers
  File "/home/fffan/下载/onnx-tensorflow-rel-1.6.0/onnx_tf/common/handler_helper.py", line 3, in <module>
    from onnx_tf.handlers.backend import *  # noqa
  File "/home/fffan/下载/onnx-tensorflow-rel-1.6.0/onnx_tf/handlers/backend/hardmax.py", line 3, in <module>
    import tensorflow_addons as tfa
  File "/home/fffan/.pyenv/versions/fffan_37/lib/python3.7/site-packages/tensorflow_addons/__init__.py", line 21, in <module>
    from tensorflow_addons import activations
  File "/home/fffan/.pyenv/versions/fffan_37/lib/python3.7/site-packages/tensorflow_addons/activations/__init__.py", line 17, in <module>
    from tensorflow_addons.activations.gelu import gelu
  File "/home/fffan/.pyenv/versions/fffan_37/lib/python3.7/site-packages/tensorflow_addons/activations/gelu.py", line 27, in <module>
    @tf.keras.utils.register_keras_serializable(package="Addons")
  File "/home/fffan/.pyenv/versions/fffan_37/lib/python3.7/site-packages/tensorflow/python/util/deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow.python.keras.api._v1.keras.utils' has no attribute 'register_keras_serializable'

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.7
 - ONNX version: 1.7
 - ONNX-TF version: 1.6.0
 - Tensorflow version: 1.14.0

**Additional context**
onnx op_version == 11
Please tell me how to fix this problem, thank you.

**Comment by cjnjuwhy** [comment]
hi, I have the same problem as yours, but a little bit different, my TensorFlow version is 2.0.0
so, have you solved this problem?
thx

**Comment by NicolaCovallero** [comment]
Hi, I have the same problem with tf2.2.0, can you post how you solved the problem?

**Comment by pmj714** [comment]
Hi, so I just struggled with this problem for a few days. Here is how I solved it: it turns out I was using the wrong python folder. I was dealing with conda environments and had everything installed on my conda environment but was using the default path to my local installation of python as a kernel. I fixed this by changing what kernel I was using with my jupyter notebook to be my conda environment. 
While you may not have the exact same issue, I can almost 100% guarantee that it has to do with your environment and installation of tensorflow.  Make sure that the directory referenced in the error, (the path to gelu.py) is the same directory that you are installing tensorflow in.

**Comment by mahamatnoumai** [comment]
> Hi, I have the same problem with tf2.2.0, can you post how you solved the problem?
@NicolaCovallero 
Hi there, I am having the same issues too with tf2.0.0. any idea how u went through.

**Comment by Emmahan11** [comment]
Hi, I have the same problem with tf1.14,.0 could you post how you solved the problem?

**Comment by Emmahan11** [comment]
#from tensorflow_addons.image import sparse_image_warp
modify as
import tensorflow as tf
tf.contrib.image.sparse_image_warp
has solved.

**Comment by xihajun** [comment]
Hi, I have the same problem with tf1.15.2 could you post how you solved the problem?

**Comment by xihajun** [comment]
Looks like tensorflow 2.5+ have the attribute: https://www.tensorflow.org/versions/r2.5/api_docs/python/tf/keras/utils/register_keras_serializable

However, we cannot find one from tf1.15

**Comment by 24kb-star** [comment]
> 
Hi, have you found a solution to convert onnx to tf1.15.2?
