### ISSUE TITLE
KeyError: 'com.mathworks'

### ISSUE THREAD

**Issue by Kottarashky** [onnx/onnx-tensorflow#698]
**Describe the bug**

Error while converting YOLO v2 onnx weights to tensorflow. Parent environment is MATLAB 2019a

**To Reproduce**

import onnx
from onnx_tf.backend import prepare
import warnings
import tensorflow as tf

warnings.filterwarnings('ignore')
model = onnx.load('D:\Projects\YOLO\YOLOv2_1.1.onnx')
tf_rep = prepare(model)

> 2020-07-10 15:03:09.109736: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x214cdf3deb0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-10 15:03:09.142636: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-10 15:03:09.163349: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-07-10 15:03:09.183310: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-10 15:03:09.222018: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-4T075BL
2020-07-10 15:03:09.242783: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-4T075BL
Traceback (most recent call last):
  File "D:\Projects\YOLO\ONNX_1.0\ONNX_1.0\ONNX_1.0.py", line 10, in <module>
    tf_rep = prepare(model)
  File "c:\windows\system32\onnx\onnx-tensorflow\onnx_tf\backend.py", line 66, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "c:\windows\system32\onnx\onnx-tensorflow\onnx_tf\backend.py", line 86, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "c:\windows\system32\onnx\onnx-tensorflow\onnx_tf\backend.py", line 147, in _onnx_graph_to_tensorflow_rep
    strict=strict)
  File "c:\windows\system32\onnx\onnx-tensorflow\onnx_tf\backend.py", line 250, in _onnx_node_to_tensorflow_op
    handler = handlers[node.domain].get(node.op_type, None)
KeyError: 'com.mathworks'

This section can be obtained by running `get_version.py` from util folder.
 - Python version:  3.6
 - ONNX version: 1.7.0
 - ONNX-TF version: 1.6.0
 - Tensorflow version: 2.2.0

**Comment by Kottarashky** [comment]
The issue was because of matlab version 2019a. 2020a is OK for now...
