### ISSUE TITLE
Conversion leads to invalid .pb format

### ISSUE THREAD

**Issue by AIshutin** [onnx/onnx-tensorflow#707]
**Describe the bug**

Conversion of working ONNX models produces invalid .pb file, which can not be read correctly by TensorFlow. (The parser raises an error)

**To Reproduce**

Requirements Installation
```
!pip install torch transformers
!pip install transformers onnxruntime-gpu onnx psutil matplotlib
!apt-get install protobuf-compiler libprotoc-dev
!git clone https://github.com/onnx/onnx.git && cd onnx && git submodule update --init --recursive && pip install -e .
!pip3 install tensorflow-addons
!git clone https://github.com/onnx/onnx-tensorflow.git && cd onnx-tensorflow && pip install -e .
```
Conversion from PyTorch code (just in case you need)
```
from transformers.convert_graph_to_onnx import convert
!rm onnx2/*
# Handles all the above steps for you
model_type = 'bert-base-uncased'
convert(framework="pt", model=model_type, output=f"onnx2/bert.onnx", opset=11)
```

The Conversion
```
!onnx-tf convert -i onnx2/bert.onnx -o saved_model.pb
```

The Failure
```
!saved_model_cli  show --dir . # fails
import tensorflow as tf
reloaded = tf.saved_model.load('.') # also fails
```

The Error
```
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:603] String field 'tensorflow.MetaGraphDef.MetaInfoDef.meta_graph_version' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
Traceback (most recent call last):
  File "/usr/local/bin/saved_model_cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_cli.py", line 990, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_cli.py", line 697, in show
    _show_tag_sets(args.dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_cli.py", line 62, in _show_tag_sets
    tag_sets = saved_model_utils.get_saved_model_tag_sets(saved_model_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_utils.py", line 88, in get_saved_model_tag_sets
    saved_model = read_saved_model(saved_model_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_utils.py", line 65, in read_saved_model
    raise IOError("Cannot parse file %s: %s." % (path_to_pb, str(e)))
IOError: Cannot parse file ./saved_model.pb: Error parsing message.
```

**ONNX model file**

https://drive.google.com/file/d/1ICIE9b_0SgJFeatlXtYIKZc2DyIES_r7/view?usp=sharing

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6.9
 - ONNX version: 1.7.0
 - ONNX-TF version: 1.6.0
 - Tensorflow version: 2.2.0

**Additional context**

**Comment by chinhuang007** [comment]
The output pb file is currently a Tensorflow protobuf for the graph, not a saved model. A PR is in progress to support saved model, https://github.com/onnx/onnx-tensorflow/pull/603

**Comment by AIshutin** [comment]
Oops.. Thank you.
