### ISSUE TITLE
'bias_2:0' is not a valid node name issue in TF 1.x

### ISSUE THREAD

**Issue by amitrokade47** [onnx/onnx-tensorflow#712]
```
import onnx,onnx_tf

def main():
    onnx_model = onnx.load("sample_mnist.onnx")
    tf_rep = onnx_tf.backend.prepare(onnx_model)
    graph_def = tf_rep.graph.as_graph_def()
    for input_node in tf_rep.inputs:
        # Make sure port number is stripped if it has any
        input_node = input_node.split(":")[0]
        assert (tf_rep.graph.get_operation_by_name(input_node).type == "Placeholder")
        fetched_ip_tensor_names = tf_rep.graph.get_operation_by_name(
            input_node).outputs[0].name
        print(fetched_ip_tensor_names)

if __name__ == '__main__':
    main()


```
gives me this error:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/amit/PycharmProjects/untitled/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 5480, in get_controller
    yield g
  File "/Users/amit/PycharmProjects/untitled/venv/lib/python3.7/site-packages/onnx_tf/backend.py", line 106, in _onnx_graph_to_tensorflow_rep
    graph_def.initializer)
  File "/Users/amit/PycharmProjects/untitled/venv/lib/python3.7/site-packages/onnx_tf/backend.py", line 212, in _onnx_initializer_to_input_dict_items
    name=init.name)) for init in initializer]
  File "/Users/amit/PycharmProjects/untitled/venv/lib/python3.7/site-packages/onnx_tf/backend.py", line 212, in <listcomp>
    name=init.name)) for init in initializer]
  File "/Users/amit/PycharmProjects/untitled/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 161, in constant_v1
    allow_broadcast=False)
  File "/Users/amit/PycharmProjects/untitled/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 271, in _constant_impl
    name=name).outputs[0]
  File "/Users/amit/PycharmProjects/untitled/venv/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/amit/PycharmProjects/untitled/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/Users/amit/PycharmProjects/untitled/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/Users/amit/PycharmProjects/untitled/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1695, in __init__
    raise ValueError("'%s' is not a valid node name" % node_def.name)

 - Python version: 3.6
[sample_mnist.onnx.zip](https://github.com/onnx/onnx-tensorflow/files/4961343/sample_mnist.onnx.zip)

 - ONNX version: 1.6.0
 - ONNX-TF version: 1.5.0
 - Tensorflow version:  1.15

(I have attached the onnx file I am working on)

I think it's related to this issue [https://github.com/onnx/onnx-tensorflow/issues/609](url) , Is there a fix for 1.x branch?

**Comment by chinhuang007** [comment]
It is fixed in https://github.com/onnx/onnx-tensorflow/pull/679, waiting for approval.
