### ISSUE TITLE
Cannot convert onnx to tf

### ISSUE THREAD

**Issue by adizhol** [onnx/onnx-tensorflow#723]
Hello,

I'm trying to convert a ResNet ONNX model to tf from https://github.com/onnx/models/tree/master/vision/classification/resnet, 
but I'm getting this error:

```
python3.6/site-packages/onnx/__init__.py:95: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  decoded = cast(Optional[int], proto.ParseFromString(s))
Traceback (most recent call last):
  File "/Users/XX/opt/miniconda3/envs/adi/bin/onnx-tf", line 11, in <module>
    load_entry_point('onnx-tf', 'console_scripts', 'onnx-tf')()
  File "/private/tmp/onnx-tensorflow/onnx_tf/cli.py", line 20, in main
    return onnx_tf.converter.main(args[1:])
  File "/private/tmp/onnx-tensorflow/onnx_tf/converter.py", line 20, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/private/tmp/onnx-tensorflow/onnx_tf/converter.py", line 132, in convert
    onnx_model = onnx.load(infile)
  File "/Users/XX/opt/miniconda3/envs/adi/lib/python3.6/site-packages/onnx/__init__.py", line 115, in load_model
    model = load_model_from_string(s, format=format)
  File "/Users/XX/opt/miniconda3/envs/adi/lib/python3.6/site-packages/onnx/__init__.py", line 152, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "/Users/XX/opt/miniconda3/envs/adi/lib/python3.6/site-packages/onnx/__init__.py", line 99, in _deserialize
    decoded, len(s)))
google.protobuf.message.DecodeError: Protobuf decoding consumed too few bytes: 17 out of 100310
```

I have cloned the tf-1.x branch like mentioned in another issue

tensorflow 1.14.0 (cpu)
onnx 1.7.0
python 3.6
conda env
macOS 10.15.6

**Comment by pluradj** [comment]
I attempted to recreate your issue, but I was able to convert all of the resnet onnx models with onnx 1.7.0, tensorflow 1.15.3, and the current onnx-tf `tf-1.x` branch.

Is there a specific model that failed or did all of them fail?

What is the version of your miniconda3 environment?
What is the version of protobuf? pip installed 3.13.0 in my environment.
What is the protobuf compiler version, `protoc --version`? I installed `libprotoc 3.9.2` locally from source code.

**Comment by padmasreenagarajan** [comment]
Im trying to convert Mobilenetv3 onnx model to tensorflow.
I need tensorflow==1.12.0 for my inferencing.
I searched all over to find the onnx and onnx-tf versions corresponding to tensorflow==1.12.0

Could you please suggest me the compatible versions of onnx,onnx-tf and torch for my required tensorflow version?
@pluradj

**Comment by pluradj** [comment]
@padmasreenagarajan Check out the [version matrix](https://github.com/onnx/onnx-tensorflow/blob/master/Versioning.md). There isn't an exact match on tensorflow 1.12.0, but I'd suggest you give onnx 1.3.0 and onnx-tf 1.3.0 since those were released most closely to your target TF release.

Also, I'd suggest that you open a new issue for your question next time rather than posting your question as a comment on other issues.

**Comment by padmasreenagarajan** [comment]
Okay..sure..will follow the same..
thank you @pluradj
