### ISSUE TITLE
Unable to Convert Pytorch Model to Tensorflow 1.8

### ISSUE THREAD

**Issue by smadan17** [onnx/onnx-tensorflow#736]
**Describe the bug**

Hi Team, I am currently having troubles trying to convert a Pytorch Resnet model to Tensorflow 1.8 model. 

**To Reproduce**

Please give us instructions to reproduce your problem.
I have converted the Pytorch model to a ONNX 1.7 model but am having troubles converting this ONNX model to Tensorflow 1.8. I specifically have been trying to use onnx-tf release 1.1.2

I am currently getting the following error:
`/code/venvs/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/code/venvs/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/code/venvs/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/code/venvs/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/code/venvs/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/code/venvs/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/common/__init__.py:87: UserWarning: FrontendHandler.get_outputs_names is deprecated. It will be removed in future release.. Use node.outputs instead.
  warnings.warn(message)
/code/venvs/venv/lib/python3.6/site-packages/torch/onnx/symbolic_helper.py:253: UserWarning: You are trying to export the model with onnx:Resize for ONNX opset version 10. This operator might cause results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
We recommend using opset 11 and above for models using this operator. 
  "" + str(_export_onnx_opset_version) + ". "
None
/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/common/handler_helper.py:73: UserWarning: Unknown op ConstantFill in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/common/handler_helper.py:73: UserWarning: Unknown op ConstantLike in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/common/handler_helper.py:73: UserWarning: Unknown op DynamicSlice in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/common/handler_helper.py:73: UserWarning: Unknown op ImageScaler in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
2020-08-19 22:30:59.280904: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
Traceback (most recent call last):
  File "convert_pytorch_model_to_tensorflow-1.8.py.py", line 152, in <module>
    tf_rep = prepare(onnx_model, strict=False)
  File "/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/backend.py", line 55, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/backend.py", line 75, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/backend.py", line 129, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/backend.py", line 224, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/handlers/handler.py", line 61, in handle
    exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type, cls.SINCE_VERSION)
  File "/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/common/exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "/code/venvs/venv/lib/python3.6/site-packages/onnx_tf/common/exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError: BatchNormalization version 9 is not implemented.`

Would someone be able to explain what the error exactly means here as well if there are other options we can consider to be able to avoid using BatchNormalization. Thanks!

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6.9
 - ONNX version: 1.7.0
 - ONNX-TF version: 1.1.2
 - Tensorflow version: 1.8

**Additional context**

**Comment by chinhuang007** [comment]
Since your ONNX model is 1.7.0, the older version of ONNX-TF such as 1.1.2 won't work. The most current ONNX-TF is 1.6.0 for which you can build from source using the tag. The master branch should work too. However that means Tensorflow needs upgrade to 2.x. If you must stay with Tensorflow 1.x, try the tf-1.x branch which was tested with Tensorflow 1.15.

**Comment by padmasreenagarajan** [comment]
Hi..
Im trying to convert Mobilenetv3 onnx model to tensorflow.
I need tensorflow==1.12.0 for my inferencing.
I searched all over to find the onnx and onnx-tf versions corresponding to tensorflow==1.12.0

Could you please suggest me the compatible versions of onnx,onnx-tf and torch for my required tensorflow version? @chinhuang007 @smadan17
