### ISSUE TITLE
SSD Mobilenet v1 from ONNX model zoo conversion fails

### ISSUE THREAD

**Issue by tmoreau89** [onnx/onnx-tensorflow#742]
**Describe the bug**
Output of the stack trace:
```
2020-08-26 21:44:09,803 - onnx-tf - INFO - Start converting onnx pb to tf pb:
Traceback (most recent call last):
  File "/home/octoml/.pyenv/versions/3.7.6/bin/onnx-tf", line 11, in <module>
    load_entry_point('onnx-tf', 'console_scripts', 'onnx-tf')()
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/cli.py", line 20, in main
    return onnx_tf.converter.main(args[1:])
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/converter.py", line 20, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/converter.py", line 137, in convert
    tf_rep = backend.prepare(onnx_model, **kwargs)
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/backend.py", line 70, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/backend.py", line 90, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/backend.py", line 151, in _onnx_graph_to_tensorflow_rep
    strict=strict)
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/backend.py", line 257, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/handlers/handler.py", line 59, in handle
    return ver_handle(node, **kwargs)
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/handlers/backend/loop.py", line 106, in version_1
    return cls._common(node, **kwargs)
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/handlers/backend/loop.py", line 90, in _common
    maximum_iterations=M)
  File "/home/octoml/.pyenv/versions/3.7.6/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/home/octoml/.pyenv/versions/3.7.6/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2491, in while_loop_v2
    return_same_structure=True)
  File "/home/octoml/.pyenv/versions/3.7.6/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2688, in while_loop
    back_prop=back_prop)
  File "/home/octoml/.pyenv/versions/3.7.6/lib/python3.7/site-packages/tensorflow/python/ops/while_v2.py", line 196, in while_loop
    add_control_dependencies=add_control_dependencies)
  File "/home/octoml/.pyenv/versions/3.7.6/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/octoml/.pyenv/versions/3.7.6/lib/python3.7/site-packages/tensorflow/python/ops/while_v2.py", line 174, in wrapped_body
    outputs = body(*_pack_sequence_as(orig_loop_vars, args))
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/handlers/backend/loop.py", line 46, in run_subgraph
    opset=current_opset)
  File "/home/octoml/Projects/onnx-tensorflow/onnx_tf/backend.py", line 318, in onnx_graph_to_tensorflow_ops
    subgraph_tensor_dict[i_name] = tensor_dict[i_name]
KeyError: 'const_slice__133'
```

**To Reproduce**
Run the following commands:
```
wget https://github.com/onnx/models/raw/master/vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_10.tar.gz
tar -zxvf ssd_mobilenet_v1_10.tar.gz
cd ssd_mobilenet_v1
onnx-tf convert -i ssd_mobilenet_v1.onnx -o model.pb
```

**ONNX model file**

Model to export: https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/ssd-mobilenetv1

**Python, ONNX, ONNX-TF, Tensorflow version**

Python version:
3.7.6 (default, Jun 29 2020, 15:13:26)
[GCC 7.5.0]
ONNX version:
1.7.0
ONNX-TF version:
1.6.0
Tensorflow version:
2.2.0

**Additional context**

**Comment by chinhuang007** [comment]
@winnietsang looks like something to do with the body graph in loop operator. Could you please take a look? Thanks!

**Comment by winnietsang** [comment]
@tmoreau89 and @chinhuang007 PR #753 will fix the issue defined above. But there are couple more issues are discovered while running the above model. I need to investigate more about them before we can support this model.

**Comment by tmoreau89** [comment]
@winnietsang thank you for the update 👍

**Comment by winnietsang** [comment]
@tmoreau89 PR #753 should fix the issue you described above. If you still experience any problem please let me know, thanks.

**Comment by tmoreau89** [comment]
Thank you @winnietsang for following up, I'll test it out.
