### ISSUE TITLE
fairseq -> onnx -> tensorflow: Error: Node 'MatMul_666': Unknown input node 'Transpose_639'

### ISSUE THREAD

**Issue by amancini-N** [onnx/onnx-tensorflow#759]
**Describe the bug**

I converted a Transformer wmt.16 from fairseq hub to onnx. Then I converted from onnx to tf. Conversion went well and .pb is produced, but then I've got this error when importing the tensorflow graph:

```
Traceback (most recent call last):
  File "/home/user/onnx-tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'MatMul_666': Unknown input node 'Transpose_639'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/onnx-tensorflow/test/test_load_converted.py", line 41, in test_load_converted_models
    g = self.load_graph(out_model)
  File "/home/user/onnx-tensorflow/test/test_load_converted.py", line 25, in load_graph
    tf.import_graph_def(graph_def)
  File "/home/user/onnx-tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/user/onnx-tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/user/onnx-tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Node 'MatMul_666': Unknown input node 'Transpose_639'
```

**To Reproduce**

```
import os
import subprocess
import unittest

import tensorflow as tf
import onnx
from onnx_tf.backend import prepare

class TestLoadConverted(unittest.TestCase):

# to load protobuf file from disk and get a Graph object in TF
    def load_graph(self, model_file):
        graph = tf.Graph()
        graph_def = tf.core.framework.graph_pb2.GraphDef()
        with open(model_file, "rb") as f:
            graph_def.ParseFromString(f.read())
            with graph.as_default():
                tf.import_graph_def(graph_def)
                return graph


    def test_load_converted_models(self):
        """
        Take a stored ONNX model, convert to TF and load into TF Graph
        """
        in_model = <PATH_TO_ONNX_MODEL>
        onnx_model = onnx.load(in_model)
        tf_rep = prepare(onnx_model)  # prepare tf representation
        out_model = <PATH_TO_OUTPUT_TF_GRAPH>
        tf_rep.export_graph(out_model)  # export the model
        g = self.load_graph(out_model)
        self.assertEqual(type(g),  tf.python.framework.ops.Graph)

if __name__ == '__main__':
    unittest.main()
```

**ONNX model file**

https://drive.google.com/file/d/1zmZEoSJIvoFpbzoqc6KLVkc08dMQu42L/view?usp=sharing

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6.9
 - ONNX version: 1.7.0
 - ONNX-TF version: 1.6.0
 - Tensorflow version: 2.2.0

**Additional context**

**Comment by winnietsang** [comment]
@amancini-N We updated our code base to export in SavedModel format now. I can't recreate your error with the new code. May you please run your model again with our master code. If you still experience any problem please let us know.

**Comment by amancini-N** [comment]
I can confirm converted tf model is working with latest master. Thanks a lot!
