### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'Tensor'

### ISSUE THREAD

**Issue by amandazw** [onnx/onnx-tensorflow#765]
the model link：https://github.com/ouyanghuiyu/chineseocr_lite/blob/onnx/models/dbnet.onnx

environment：
onnx-tf              1.5.0
tensorflow           1.15.0

Skipping registering GPU devices...
2020-09-18 10:29:44.834707: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-18 10:29:44.834724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 2 3 
2020-09-18 10:29:44.834738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N N Y 
2020-09-18 10:29:44.834747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N Y N 
2020-09-18 10:29:44.834759: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 2:   N Y N N 
2020-09-18 10:29:44.834772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 3:   Y N N N 
Traceback (most recent call last):
  File "/home/bigdata/.conda/envs/zw_py361/bin/onnx-tf", line 11, in <module>
    sys.exit(main())
  File "/home/bigdata/.conda/envs/zw_py361/lib/python3.6/site-packages/onnx_tf/cli.py", line 20, in main
    return onnx_tf.converter.main(args[1:])
  File "/home/bigdata/.conda/envs/zw_py361/lib/python3.6/site-packages/onnx_tf/converter.py", line 20, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/home/bigdata/.conda/envs/zw_py361/lib/python3.6/site-packages/onnx_tf/converter.py", line 133, in convert
    tf_rep = backend.prepare(onnx_model, **kwargs)
  File "/home/bigdata/.conda/envs/zw_py361/lib/python3.6/site-packages/onnx_tf/backend.py", line 65, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/bigdata/.conda/envs/zw_py361/lib/python3.6/site-packages/onnx_tf/backend.py", line 85, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/bigdata/.conda/envs/zw_py361/lib/python3.6/site-packages/onnx_tf/backend.py", line 143, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/home/bigdata/.conda/envs/zw_py361/lib/python3.6/site-packages/onnx_tf/backend.py", line 238, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/home/bigdata/.conda/envs/zw_py361/lib/python3.6/site-packages/onnx_tf/handlers/handler.py", line 61, in handle
    return ver_handle(node, **kwargs)
  File "/home/bigdata/.conda/envs/zw_py361/lib/python3.6/site-packages/onnx_tf/handlers/backend/upsample.py", line 68, in version_9
    new_h_w_shape = tf.cast(h_w_scale * h_w_shape, tf.int32)
TypeError: can't multiply sequence by non-int of type 'Tensor'

**Comment by pluradj** [comment]
Thanks for providing your model. I was able to convert it by starting from onnx-tensorflow [`v1.6.0-tf-1.15`](https://github.com/onnx/onnx-tensorflow/tree/v1.6.0-tf-1.15) tag and applying the fixes for dynamic shapes in PR #762 and PR #766.
