### ISSUE TITLE
TypeError: Value passed to parameter 'input' has DataType bool not in list of allowed values

### ISSUE THREAD

**Issue by GotG** [onnx/onnx-tensorflow#802]
hello
getting this error:
`Traceback (most recent call last):
  File "/usr/local/bin/onnx-tf", line 33, in <module>
    sys.exit(load_entry_point('onnx-tf', 'console_scripts', 'onnx-tf')())
  File "/content/onnx-tensorflow/onnx_tf/cli.py", line 20, in main
    return onnx_tf.converter.main(args[1:])
  File "/content/onnx-tensorflow/onnx_tf/converter.py", line 20, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/content/onnx-tensorflow/onnx_tf/converter.py", line 136, in convert
    tf_rep = backend.prepare(onnx_model, **kwargs)
  File "/content/onnx-tensorflow/onnx_tf/backend.py", line 66, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/content/onnx-tensorflow/onnx_tf/backend.py", line 86, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/content/onnx-tensorflow/onnx_tf/backend.py", line 147, in _onnx_graph_to_tensorflow_rep
    strict=strict)
  File "/content/onnx-tensorflow/onnx_tf/backend.py", line 253, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/content/onnx-tensorflow/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/content/onnx-tensorflow/onnx_tf/handlers/backend/min.py", line 34, in version_8
    return cls._common(node, **kwargs)
  File "/content/onnx-tensorflow/onnx_tf/handlers/backend/min.py", line 21, in _common
    node, inputs=[tf.stack(values)], **kwargs)
  File "/content/onnx-tensorflow/onnx_tf/handlers/backend_handler.py", line 111, in make_tensor_from_onnx_node
    return cls._run_tf_func(tf_func, inputs, attrs)
  File "/content/onnx-tensorflow/onnx_tf/handlers/backend_handler.py", line 188, in _run_tf_func
    return tf_func(**kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/math_ops.py", line 2090, in reduce_min_v1
    return reduce_min(input_tensor, axis, keepdims, name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/math_ops.py", line 2126, in reduce_min
    name=name))
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/gen_math_ops.py", line 6475, in _min
    name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/op_def_library.py", line 632, in _apply_op_helper
    param_name=input_name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/op_def_library.py", line 61, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'input' has DataType bool not in list of allowed values: float32, float64, int32, uint8, int16, int8, complex64, int64, qint8, quint8, qint32, bfloat16, uint16, complex128, float16, uint32, uint64`

tf: 1.15.2
version = '1.6.0'
git_version = '6b9e76d6fca74d5ddbf47049b9670120abaaf70f'
thanks!

**Comment by chinhuang007** [comment]
Based on the error message, you have "bool" as input type for the min operator, which is not supported by either ONNX or Tensorflow. Please make sure the input has a numeric type.

**Comment by GotG** [comment]
so i converted this model from pytorch. this means that if possible i should replace the op in the pytorch model?
thank you
