### ISSUE TITLE
Crop is not implemented

### ISSUE THREAD

**Issue by a-zh** [onnx/onnx-tensorflow#807]
**Describe the bug**

I can't convert my onnx model with the current messages:
Warning: Checker does not support models with experimental ops: Crop

```
2020-11-16 15:25:26,049 - onnx-tf - DEBUG - Fail to get since_version of ThresholdedRelu in domain `` with max_inclusive_version=8. Set to 1.
2020-11-16 15:25:26,050 - onnx-tf - DEBUG - Fail to get since_version of Where in domain `` with max_inclusive_version=8. Set to 1.
2020-11-16 15:25:26.053911: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-11-16 15:25:26.054407: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-11-16 15:25:26.054861: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-F5GUC66): /proc/driver/nvidia/version does not exist
2020-11-16 15:25:26.055594: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-11-16 15:25:26.063005: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1992000000 Hz
2020-11-16 15:25:26.064648: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f2786f6c200 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-16 15:25:26.065054: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/home/zhukov/.local/bin/onnx-tf", line 8, in <module>
    sys.exit(main())
  File "/home/zhukov/.local/lib/python2.7/site-packages/onnx_tf/cli.py", line 20, in main
    return onnx_tf.converter.main(args[1:])
  File "/home/zhukov/.local/lib/python2.7/site-packages/onnx_tf/converter.py", line 20, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/home/zhukov/.local/lib/python2.7/site-packages/onnx_tf/converter.py", line 135, in convert
    tf_rep.export_graph(outdir)
  File "/home/zhukov/.local/lib/python2.7/site-packages/onnx_tf/backend_rep.py", line 116, in export_graph
    **self.signatures))
  File "/home/zhukov/.local/lib/python2.7/site-packages/tensorflow_core/python/eager/def_function.py", line 909, in get_concrete_function
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/zhukov/.local/lib/python2.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/home/zhukov/.local/lib/python2.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/zhukov/.local/lib/python2.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/zhukov/.local/lib/python2.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/zhukov/.local/lib/python2.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/zhukov/.local/lib/python2.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/zhukov/.local/lib/python2.7/site-packages/tensorflow_core/python/eager/function.py", line 3211, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/home/zhukov/.local/lib/python2.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
onnx.backend.test.runner.BackendIsNotSupposedToImplementIt: in converted code:

    /home/zhukov/.local/lib/python2.7/site-packages/onnx_tf/backend_tf_module.py:98 __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    /home/zhukov/.local/lib/python2.7/site-packages/onnx_tf/backend.py:291 _onnx_node_to_tensorflow_op  *
        raise BackendIsNotSupposedToImplementIt("{} is not implemented.".format(

    BackendIsNotSupposedToImplementIt: Crop is not implemented.
```

Is any plans for supporting Crop?

**Comment by chinhuang007** [comment]
Crop is an experimental op and removed since ONNX version 1.5. I suggest to create a new model using more recent ONNX version and opset number. The replacement for experimental ops is documented here, https://github.com/onnx/onnx/blob/master/docs/ManagingExperimentalOps.md

**Comment by a-zh** [comment]
OK. Thank you very much!
