### ISSUE TITLE
onnx->TensorFlow BatchNormalization@0' is not a valid scope name

### ISSUE THREAD

**Issue by ZHR1997** [onnx/onnx-tensorflow#821]
import onnx
from onnx_tf.backend import prepare
onnx_model = onnx.load("ch_mobile_infer_clipChanged.onnx")
tf_rep = prepare(onnx_model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/zhr/onnx-tensorflow/onnx_tf/backend.py", line 66, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/zhr/onnx-tensorflow/onnx_tf/backend.py", line 86, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/zhr/onnx-tensorflow/onnx_tf/backend.py", line 147, in _onnx_graph_to_tensorflow_rep
    strict=strict)
  File "/zhr/onnx-tensorflow/onnx_tf/backend.py", line 253, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/zhr/onnx-tensorflow/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/zhr/onnx-tensorflow/onnx_tf/handlers/backend/batch_normalization.py", line 73, in version_9
    return cls._common(node, **kwargs)
  File "/zhr/onnx-tensorflow/onnx_tf/handlers/backend/batch_normalization.py", line 48, in _common
    return [cls.make_tensor_from_onnx_node(node, inputs=inputs)]
  File "/zhr/onnx-tensorflow/onnx_tf/handlers/backend_handler.py", line 111, in make_tensor_from_onnx_node
    return cls._run_tf_func(tf_func, inputs, attrs)
  File "/zhr/onnx-tensorflow/onnx_tf/handlers/backend_handler.py", line 188, in _run_tf_func
    return tf_func(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_impl.py", line 1427, in batch_normalization
    with ops.name_scope(name, "batchnorm", [x, mean, variance, scale, offset]):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 6346, in __enter__
    return self._name_scope.__enter__()
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 4129, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'BatchNormalization@0' is not a valid scope name

onnx 1.7.0
onnx-tf 1.6.0
tensorflow 1.15.0

how to fix this problem

**Comment by chinhuang007** [comment]
@ZHR1997 can you provide onnx file for debugging purpose?

**Comment by ZHR1997** [comment]
> @ZHR1997 can you provide onnx file for debugging purpose?

ok  how to provide it to you

**Comment by chinhuang007** [comment]
Put it on a shared place like google drive. Please make sure it is publicly accessible. Thanks.

**Comment by fupingren** [comment]
have you resolved this issue?

**Comment by vvhaha** [comment]
have you resolved this issue?
