### ISSUE TITLE
Running converted pb file issue

### ISSUE THREAD

**Issue by seongkyun** [onnx/onnx-tensorflow#835]
**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6
 - ONNX version: torch==1.2.0, onnx==1.8.0
 - ONNX-TF version: onnx-tf==1.7
 - Tensorflow version: tensorflow-gpu==2.3.1

I have onnx object detection model and ran the model as tensorflow-backend below:
<pre><code>
import onnx
from onnx_tf.backend import prepare
...
onnx_model = onnx.load("MODEL_PATH.onnx")
outputs = prepare(onnx_model).run(inputs)
...
</code></pre>

and it was successfully ran with correct predicts. :)

after it, i tried onnx model to tensorflow model (pb file) below:

<pre><code>
import onnx
from onnx_tf.backend import prepare
INPUT_ONNX_PATH = "blahblah.onnx"
OUTPUT_TF_PATH = "./"
onnx_model = onnx.load(INPUT_ONNX_PATH)  # load onnx model
tf_rep = prepare(onnx_model)  # prepare tf representation
tf_rep.export_graph(OUTPUT_TF_PATH)  # export the model
</code></pre>

and got the saved_model.pb file, assets folder, and variables folder.

finally, i tried to run my model with only tensorflow api 

<pre><code>
import tensorflow as tf
...
model = tf.saved_model.load(PB_MODEL_PATH)
outputs = model(input) # ERROR HERE!
...
</code></pre>

and got following errors

<pre><code>

Traceback (most recent call last):
  File "tf_backbone.py", line 381, in <module>
    outputs = model(images)
  File "/home/han/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 509, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/home/han/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/han/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/han/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/home/han/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/han/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/han/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/han/.local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/han/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/han/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 257, in restored_function_body
    "\n\n".join(signature_descriptions)))
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * Tensor("None_0:0", shape=(1, 3, 320, 512), dtype=float32)
  Keyword arguments: {}

Expected these arguments to match one of the following 1 option(s):

Option 1:
  Positional arguments (0 total):
    *
  Keyword arguments: {'actual_input_1': TensorSpec(shape=(1, 3, 320, 512), dtype=tf.float32, name='actual_input_1')}
</code></pre>

I made my input is maden following below:

<pre><code>
import cv2
image = cv2.imread(IMAGE_PATH,  cv2.IMREAD_COLOR)
# do preproc
...
input = tf.convert_to_tensor(image)
print(input.shape) # (1, 3, 320, 512)
...
</code></pre>

my original onnx model has exact same input and ran well...

So my question is,

what should i do to inference on pb file with tensorflow??

how could i do that?

please help me guys :)

**Comment by seongkyun** [comment]
I have solved it.

type below at terminal then you can see the I/O shapes of the model:
`$ saved_model_cli show --dir PATH/TO/PB/FILE --tag_set serve --signature_def serving_default`
the PATH/TO/PB/FILE is the folder including asset, variables folders and saved_model.pb file.

inside of the code, I have changed from:
<pre><code>
import tensorflow as tf
...
model = tf.saved_model.load(PB_MODEL_PATH)
outputs = model(input) # ERROR HERE!
...
</code></pre>

to:
<pre><code>
import tensorflow as tf
...
model = tf.saved_model.load(PB_MODEL_PATH)
inference = model.signatures["serving_default"]
outputs = inference(input) # ERROR HERE!
...
</code></pre>

and it works!
