### ISSUE TITLE
backend.prepare(onnx_model) fails for a simple model

### ISSUE THREAD

**Issue by jonalm** [onnx/onnx-tensorflow#859]
using Python 3.7.9 with
```
onnx==1.8.0
onnx-tf==1.7.0
tensorflow==2.4.1
```

I have some issues converting a simple onnx model with the following script:

```python
import onnx
import onnx_tf.backend as backend
onnx_model = onnx.load("model.onnx")
print("onnx model is loaded:", onnx_model)
tf_rep = backend.prepare(onnx_model)
tf_rep.export_graph(".")
```

I get this error which seems to indicate that tensorflow does not support the layout of my data (?)

```
2021-01-22 13:47:55.162986: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-22 13:47:55.163632: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "convert_model.py", line 7, in <module>
    tf_rep.export_graph(".")
  File "/Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/onnx_tf/backend_rep.py", line 116, in export_graph
    **self.signatures))
  File "/Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3887, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/onnx_tf/backend_tf_module.py:98 __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/onnx_tf/backend.py:289 _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/onnx_tf/handlers/handler.py:59 handle  *
        return ver_handle(node, **kwargs)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/onnx_tf/handlers/backend/conv.py:15 version_11  *
        return cls.conv(node, kwargs["tensor_dict"])
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/onnx_tf/handlers/backend/conv_mixin.py:69 conv  *
        x = PadMixin.get_padding_as_op(x, pads)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/onnx_tf/handlers/backend/pad_mixin.py:17 get_padding_as_op  *
        return tf.pad(x, padding)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:3355 pad_v2
        return pad(tensor, paddings, mode, name, constant_values)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:3422 pad
        result = gen_array_ops.pad(tensor, paddings, name=name)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py:6485 pad
        "Pad", input=input, paddings=paddings, name=name)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:750 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py:592 _create_op_internal
        compute_device)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:3536 _create_op_internal
        op_def=op_def)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:2016 __init__
        control_input_ops, op_def)
    /Users/jonalm/.asdf/installs/python/3.7.9/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1856 _create_c_op
        raise ValueError(str(e))

    ValueError: Shape must be rank 3 but is rank 0 for '{{node Pad}} = Pad[T=DT_FLOAT, Tpaddings=DT_INT32](data_0, Const)' with input shapes: [], [3,2].
```

Is there some limitations to the onnx model for it to be tf compatible?

My model looks like this, and gets loaded by onnx without problems.

![Screenshot 2021-01-18 at 09 41 17](https://user-images.githubusercontent.com/5505854/105492753-b11ae600-5cb8-11eb-9186-68a70200a229.png)

**Comment by chinhuang007** [comment]
Is it possible to share the onnx file for debugging?

**Comment by jonalm** [comment]
Sure: https://www.dropbox.com/s/ua96uxl4gaax1ku/model.onnx?dl=0

**Comment by chinhuang007** [comment]
The input data_0, a scalar of float32, seems not valid for conv, as described in the spec, "Input data tensor from previous layer; has size (N x C x H x W), where N is the batch size, C is the number of channels, and H and W are the height and width..", https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv

**Comment by jonalm** [comment]
Oh, my bad. I've forgot to specify the input dimensions when generating the model file. I got the code to run after that modification. Many thanks for your help.
