### ISSUE TITLE
Incorrect conversion of a Pytorch model after a very slow prepare()

### ISSUE THREAD

**Issue by palonso** [onnx/onnx-tensorflow#923]
**Describe the bug**
I have an ONNX model (opset 11) exported from PyTorch's [EffficientNet](https://github.com/lukemelas/EfficientNet-PyTorch) implementation. My goal is to convert the ONNX model to TensorFLow (SavelModel) to perform inference from the C API.

When I use `onnx-tf=1.8.0` and `tensorflow==2.4.1` it takes ~20 minutes to generate the `SavedModel`, and on inference time it gets stuck for ~20 minutes, after which it throws and exception because TensorFlow is not able to find the name of the input node.

When I use `onnx-tf=1.7.0` and `tensorflow==1.15.2`, it generates a frozen model (.pb) very fast, and the inference works, but it is way slower than expected (~10 seconds to initialize, while an equivalent TensorFlow model takes 0.23s).
As mentioned in #470, by inspecting the .pb with Netron I can see that the depth-wise layers are represented as several conv operators (expected for TF 1.X).

I would like to convert de model using TF2 and, ideally, generate a model with convolutions interpreted as TensorFlow's native depth-wise convolutions.

**To Reproduce**
```python
import onnx
from onnx_tf.backend import prepare


onnx_file = "model.onnx"
tf_file = "model_tf"
onnx_model = onnx.load(onnx_file) 
tf_rep = prepare(onnx_model) 
tf_rep.export_graph(tf_file)
```
**ONNX model file**
The [ONNX model](https://drive.google.com/file/d/1GJa2m5Y-ig3xnYndCwbBjCYk8v5YYiGZ/view?usp=sharing)

**Python, ONNX, ONNX-TF, Tensorflow version**
 - Python version: 3.8.5 / 3.7.9 
 - ONNX version:  1.9.0 /  1.7.0
 - ONNX-TF version: 1.8.0 / 1.7.0
 - Tensorflow version: 2.4.1 / 1.15.2

**Comment by seanshpark** [comment]
Maybe check https://github.com/onnx/onnx-tensorflow/issues/921#issuecomment-853471398 with installing master onnx-tf
```
pip install -e git+https://github.com/onnx/onnx-tensorflow.git#egg=onnx_tf
```

**Comment by palonso** [comment]
Thanks for the fast reply. I tried installing from the master, but I got the same result.
This is the TensorFlow log I got with the `prepare` call:
```
2021-06-04 10:07:43.942965: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:absl:Found untraced functions such as gen_tensor_dict while saving (showing 1 of 1). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as gen_tensor_dict while saving (showing 1 of 1). These functions will not be directly callable after loading.
```

This is the TensorFlow log I got on inference with the SavedModel:
```
2021-06-04 10:45:40.981324: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: /home/pablo/source_models/effnet5
2021-06-04 10:45:41.078194: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 293885 microseconds.
2021-06-04 10:58:52.498972: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pablo/reps/demo/demo/run.py", line 191, in <module>
    run(parser.parse_args())
  File "/home/pablo/reps/demo/demo/run.py", line 74, in run
    source_models[tagger] = SourceModel(
  File "/home/pablo/reps/demo/demo/inference.py", line 137, in __init__
    self.model = TensorflowPredict(
  File "/usr/local/lib/python3.8/dist-packages/essentia/standard.py", line 44, in __init__
    self.configure(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/essentia/standard.py", line 64, in configure
    self.__configure__(**kwargs)
RuntimeError: Error while configuring TensorflowPredict: TensorflowPredict: 'melspectrogram' is not a valid node name of this graph.
TensorflowPredict: Available node names are:
Const, Const_1, Const_2, Const_3, Const_4, Const_5, Const_6, Const_7, Const_8, Const_9, Const_10, Const_11, Const_12, Const_13, Const_14, Const_15, Const_16, Const_17, Const_18, Const_19, Const_20, Const_21, Const_22, Const_23, Const_24, Const_25, Const_26, Const_27, Const_28, Const_29, Const_30, Const_31, Const_32, Const_33, Const_34, Const_35, Const_36, Const_37, Const_38, Const_39, Const_40, Const_41, Const_42, Const_43, Const_44, Const_45, Const_46, Const_47, Const_48, Const_49, Const_50, Const_51, Const_52, Const_53, Const_54, Const_55, Const_56, Const_57, Const_58, Const_59, Const_60, Const_61, Const_62, Const_63, Const_64, Const_65, Const_66, Const_67, Const_68, Const_69, Const_70, Const_71, Const_72, Const_73, Const_74, Const_75, Const_76, Const_77, Const_78, Const_79, Const_80, Const_81, Const_82, Const_83, Const_84, Const_85, Const_86, Const_87, Const_88, Const_89, Const_90, Const_91, Const_92, Const_93, Const_94, Const_95, Const_96, Const_97, Const_98, Const_99, Const_100, Const_101, Const_102, Const_103, Const_104, Const_105, Const_106, Const_107, Const_108, Const_109, Const_110, Const_111, Const_112, Const_113, Const_114, Const_115, Const_116, Const_117, Const_118, Const_119, Const_120, Const_121, Const_122, Const_123, Const_124, Const_125, Const_126, Const_127, Const_128, Const_129, Const_130, Const_131, Const_132, Const_133, Const_134, Const_135, Const_136, Const_137, Const_138, Const_139, Const_140, Const_141, Const_142, Const_143, Const_144, Const_145, Const_146, Const_147, Const_148, Const_149, Const_150, Const_151, Const_152, Const_153, Const_154, Const_155, Const_156, Const_157, Const_158, Const_159, Const_160, Const_161, Const_162, Const_163, Const_164, Const_165, Const_166, Const_167, Const_168, Const_169, Const_170, Const_171, Const_172, Const_173, Const_174, Const_175, Const_176, Const_177, Const_178, Const_179, Const_180, Const_181, Const_182, Const_183, Const_184, Const_185, Const_186, Const_187, Const_188, Const_189, Const_190, Const_191, Const_192, Const_193, Const_194, Const_195, Const_196, Const_197, Const_198, Const_199, Const_200, Const_201, Const_202, Const_203, NoOp, Const_204, serving_default_melspectrogram, PartitionedCall, saver_filename, StatefulPartitionedCall, StatefulPartitionedCall_1.
```
Notice that the model is stuck for 13 minutes until the exception is thrown. Also, with `onnx-tf==1.7.0` and `tensorflow==1.15`, in the produced .pb the input node is called `melspectrogram`, just as in the .onnx model that I attached above, and I can see all convolutional, dense, etc. nodes  from the TensorFlow's C API. However, with this SavedModel, I just see a bunch of constant values.  At the beginning I though that this could be due to the SavedModel format, but with a native TensorFlow SavedModel I can see all the nodes just as with the TF1 .pb files.

Here I attach the generated [SavedModel](https://drive.google.com/file/d/15Wa9VJ8m5ZV7BHY4ILSJjjmkQtD7r7zG/view?usp=sharing).

**Comment by chinhuang007** [comment]
Can you provide sample input data and code to reproduce the error?

**Comment by palonso** [comment]
I found that the model initializes in a reasonable time when doing the inference from Tensorflow's Python bindings:

```Python
import tensorflow as tf
import numpy as np

model_file = 'effnet5'
output_node = 'activations'
fake_data = np.zeros((60, 128, 96), dtype='float32')

model = tf.saved_model.load(model_file)
infer = model.signatures["serving_default"]
infer(tf.constant(fake_data))[output_node]
```

However,  when the model is loaded from the C API, it takes 13 minutes to initialize (similar to the conversion time), after which I found that inference is correct as with the Tensorflow's Python bindings.

The error I was getting is because the converted TensorFlow model expects different input/output node names:
`melspectrogram` (ONNX input) -> `serving_default_melspectrogram` (TF input)
`activations` (ONNX output) -> `PartitionedCall` (TF output)

Still, it would be great to get some ideas on why could the model take so much time to initialize. In my application, this model gets stuck on [ this call](https://github.com/tensorflow/tensorflow/blob/66de53c247e7e72c63f81acde877b5437ee4bb15/tensorflow/c/c_api.h#L1229) to TensorFlow's API, while native TensorFlow 2 SavedModels or SavedModels converted from frozen graphs (.pb) are able to load fast.

Unfortunately, my program is a bit tricky to reproduce. It requires building [Essentia](https://essentia.upf.edu/) with TensorFlow support following [these instructions](https://mtg.github.io/essentia-labs/news/tensorflow/2019/10/19/tensorflow-models-in-essentia/).
- In step 3, the code should be taken from this [Pull Request](https://github.com/MTG/essentia/pull/1161) instead of the master
- In step 4, `src/3rdparty/tensorflow/setup_from_python.sh` should be replaced by `src/3rdparty/tensorflow/setup_from_libtensorflow.sh`. And `setup_from_libtensorflow.sh` should be modified to download `libtensorflow` version 2.4.1

Then the code to reproduce the problem with our Python bindings is:
```Python
from essentia.standard import TensorflowPredict

TensorflowPredict(
    savedModel="effnet5",
    inputs=["serving_default_melspectrogram"],
    outputs=["PartitionedCall"],
)()
```

**Comment by palonso** [comment]
Hello,
lately I've been revisiting this problem, and I've found a way to reproduce it directly in TensorFlow by using the CLI tflite converter:
```bash
tflite_convert --saved_model_dir effnet --output_file effnet.tflite
```
where `effnet` is the `saved_model` version created with `onnx-tf`. The conversion process took about 20 minutes.
The conversion (`saved_model` -> `.tflite`) produces a valid `.tflite` model, but again it takes about 20 minutes to convert (while a native TensorFlow `saved_model` can be converted in few seconds). By inspecting the `.tflite` model with Netron I found that the depthwise convolution operators (what I thought that could be the cause of the problem) are correctly converted. After this, inference with `tflite` is correct and actually very fast!

This makes me think that the problem is that the saved_model is correct, but it is created in a way that the initialization is extremely slow, making it unsuitable for the C API.

I looked at the `onnx` model in Netron, but I couldn't identify any problem on it, maybe someone with more experience could spot if there are issues on it.

I provide the  [onnx](https://drive.google.com/file/d/1GJa2m5Y-ig3xnYndCwbBjCYk8v5YYiGZ/view?usp=sharing) models as exported from PyTorch, and the [saved model](https://drive.google.com/drive/folders/1F1b4OVRBfLOC6uYBz7nUhAheITWOKN_c?usp=sharing) and [.tflite](https://drive.google.com/file/d/1rf3zM1uhmambCqMoH5c8WFGkwLhXkgwv/view?usp=sharing) versions.
