### ISSUE TITLE
Couldn't convert to tensorflow successful.

### ISSUE THREAD

**Issue by eltonl2020** [onnx/onnx-tensorflow#925]
import torch
import onnx
from onnx_tf.backend import prepare

model = onnx.load('output_softmax_320.onnx')
tf_rep = prepare(model)
tf_rep.export_graph('output_softmax_320')

ONNX file link: [https://drive.google.com/file/d/1Ec6LmsrWq5T9FcHsi_JMuKsEFeOcGv39/view?usp=sharing](url)
I got the output_softmax_320 folder, but with the wrong pb file, couldn't be loaded by tensorflow.

I've tried every possible way, but still got failed.
Can someone help me? appreciate it!

**Comment by chinhuang007** [comment]
Please note that onnx-tf creates a TensorFlow SavedModel instead of a computation graph pb file since version 1.7. You can use Tensorflow saved_model APIs, https://www.tensorflow.org/api_docs/python/tf/saved_model, to load and run the model.

**Comment by eltonl2020** [comment]
Thanks.

**Comment by gcunhase** [comment]
How can I get a TF2 SavedModel using `onnx_tf`?
I'm trying to load an exported model but it's loading as `_UserObject` instead of `tf.keras.model`:
```python
import onnx
from onnx_tf.backend import prepare
import tensorflow as tf

# 1. Load onnx model
onnx_model = onnx.load(onnx_model_path)

# 2. Convert to TF
tf_rep = prepare(onnx_model)
saved_model_dir = onnx_model_path.split(".onnx")[0] + "_saved_model"
tf_rep.export_graph(saved_model_dir)

# 3. Load SavedModel
model = tf.keras.models.load_model(saved_model_dir)
input_shape = (1, 3, 800, 1280)
in_tensor = tf.random.normal(input_shape)
model(in_tensor)
print(model.summary())
```

Error:
```
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Traceback (most recent call last):
  File "/home/nvidia/PycharmProjects/nvbugs/venv38_orin/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/nvidia/PycharmProjects/nvbugs/venv38_orin/lib/python3.8/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 289, in restored_function_body
    raise ValueError(
ValueError: Could not find matching concrete function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * Tensor("None_0:0", shape=(1, 3, 800, 1280), dtype=float32)
  Keyword arguments: {}

 Expected these arguments to match one of the following 1 option(s):

Option 1:
  Positional arguments (0 total):
    * 
  Keyword arguments: {'input_1': TensorSpec(shape=(None, 3, 800, 1280), dtype=tf.float32, name='input_1')}
python-BaseException
```
