### ISSUE TITLE
Cannot convert Faster-RCNN, resulting Tensorflow model contains breaking op node

### ISSUE THREAD

**Issue by florianletsch** [onnx/onnx-tensorflow#943]
**Describe the bug**

I am trying to convert a Faster-RCNN with Resnet backbone along the following conversion path: 

1. PyTorch -> ONNX
2. ONNX -> Tensorflow
3. Tensorflow -> tflite

Step 2 and 3 take a long time (~18 minutes each on my machine). This is a little annoying, but not the issue I am writing about.
Step 3 fails with the following error message:

```
loc(callsite(callsite("onnx_tf_prefix_If_1347@__inference___call___15681" at "StatefulPartitionedCall@__inference_signature_wrapper_16224") at "StatefulPartitionedCall")): error: could not rewrite use of immutable bound input
Traceback (most recent call last):
  File "/home/florian/projects/torch2tflite-failing/venv/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 291, in toco_convert_protos
    model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
  File "/home/florian/projects/torch2tflite-failing/venv/lib/python3.8/site-packages/tensorflow/lite/python/wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc(callsite(callsite("onnx_tf_prefix_If_1347@__inference___call___15681" at "StatefulPartitionedCall@__inference_signature_wrapper_16224") at "StatefulPartitionedCall")): could not rewrite use of immutable bound input
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
```

The original PyTorch implementation I am using is the official one from `torchvision.models.detection.fasterrcnn_resnet50_fpn`, see https://pytorch.org/vision/stable/models.html for details.

**To Reproduce**

I have prepared a self-contained example to reproduce the issue:
https://github.com/florianletsch/torch2tflite-failing

It fails on `step3_tf2tflite.py`. You can see the logs at https://github.com/florianletsch/torch2tflite-failing/tree/main/logs

**ONNX model file**
The ONNX model file and Tensorflow saved model can be found here: https://florianletsch.de/media/torch2tflite-assets.zip (498 MB).

**Python, ONNX, ONNX-TF, Tensorflow version**

 - Python version: 3.8.10
 - ONNX version: 1.9.0
 - ONNX-TF version: 1.8.0
 - Tensorflow version: 2.5.0

**Additional context**

The error hints at op node `If_1347`. This node has "then" and "else" branches resulting from the folllwing two jit-exports. Maybe that's a pointer at the reason for the failure?

```
graph torch-jit-export1 {
  %2633 = Constant[value = <Tensor>]()
  %2634 = ConstantOfShape[value = <Tensor>](%2633)
  return %2634
}

graph torch-jit-export2 {
  %2635 = ReduceMax[keepdims = 0](%2622)
  %2636 = Cast[to = 1](%2626)
  %2637 = Constant[value = <Scalar Tensor []>]()
  %2638 = Cast[to = 1](%2637)
  %2639 = Add(%2635, %2638)
  %2640 = Mul(%2636, %2639)
  %2641 = Unsqueeze[axes = [1]](%2640)
  %2642 = Add(%2622, %2641)
  %2643 = Unsqueeze[axes = [0]](%2642)
  %2644 = Unsqueeze[axes = [0]](%2624)
  %2645 = Unsqueeze[axes = [0]](%2644)
  %2646 = Constant[value = <Tensor>]()
  %2647 = Constant[value = <Tensor>]()
  %2648 = NonMaxSuppression(%2643, %2645, %2646, %2647)
  %2649 = Constant[value = <Tensor>]()
  %2650 = Gather[axis = 1](%2648, %2649)
  %2651 = Squeeze[axes = [1]](%2650)
  return %2651
}
```

To be clear, it fails on step 3 (Tensorflow -> tflite). This step _technically_ only relies on Tensorflow and TFlite. 

However, the op node that causes the issue on comes from the ONNX model, so I want to understand if that is where the error originates. 

If you can give me any pointers where else to get assistance with the issue, I am all ears.

**Comment by florianletsch** [comment]
This appears to be an issue with the TFLite converter. They have added support for mutable variables in recently, only available in tf-nightly. My conversion still isn't working as it is breaking with a different error, but for now I'll assume this is unrelated to onnx or onnx-tensorflow.

Tensorflow issue: https://github.com/tensorflow/tensorflow/issues/50635
