### ISSUE TITLE
depthwise and pointwise convolution convert ONNX to tensorflow failed

### ISSUE THREAD

**Issue by shichaog** [onnx/onnx-tensorflow#995]
**Describe the bug**

depthwise and pointwise convolution convert ONNX to tensorflow failed
`Traceback (most recent call last):
  File "/Users/owen.ge/SourceCode/ai-denoise/TRU_CoreML/coremltools_torch/trutorch_convert_onnx.py", line 108, in <module>
    tf_rep.export_graph(tf_model_path)
  File "/Users/owen.ge/SourceCode/onnx-tensorflow/onnx_tf/backend_rep.py", line 132, in export_graph
    signatures=self.tf_module.__call__.get_concrete_function(
  File "/Users/owen.ge/SourceCode/venv/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 1259, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/Users/owen.ge/SourceCode/venv/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 1239, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/Users/owen.ge/SourceCode/venv/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 780, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/Users/owen.ge/SourceCode/venv/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3157, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/owen.ge/SourceCode/venv/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3557, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/owen.ge/SourceCode/venv/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3392, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/Users/owen.ge/SourceCode/venv/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1143, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/owen.ge/SourceCode/venv/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/owen.ge/SourceCode/venv/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 4095, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/Users/owen.ge/SourceCode/venv/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1129, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "/Users/owen.ge/SourceCode/onnx-tensorflow/onnx_tf/backend_tf_module.py", line 99, in __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    File "/Users/owen.ge/SourceCode/onnx-tensorflow/onnx_tf/backend.py", line 333, in _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    File "/Users/owen.ge/SourceCode/onnx-tensorflow/onnx_tf/handlers/handler.py", line 59, in handle  *
        return ver_handle(node, **kwargs)
    File "/Users/owen.ge/SourceCode/onnx-tensorflow/onnx_tf/handlers/backend/conv.py", line 11, in version_1  *
        return cls.conv(node, kwargs["tensor_dict"])
    File "/Users/owen.ge/SourceCode/onnx-tensorflow/onnx_tf/handlers/backend/conv_mixin.py", line 306, in conv  *
        output = tf.add(output, bias)

    ValueError: Dimensions must be equal, but are 512 and 64 for '{{node Add_7}} = AddV2[T=DT_FLOAT](concat_4/concat, Add_7/y)' with input shapes: [?,?,?,512], [64].`

**To Reproduce**
pls create a python file and run next script with attached unziped file model_onnx.onnx.zip in the same directory.

import onnx
model_onnx = onnx.load("model_onnx.onnx")
from onnx_tf.backend import prepare

tf_rep = prepare(model_onnx)
tf_model_path = "tf_model.pb"
tf_rep.export_graph(tf_model_path)

import tensorflow as tf
# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model(tf_model_path)
tflite_model = converter.convert()
tflite_model_path='model.tflite'
# Save the model
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

**ONNX model file**

[model_onnx.onnx.zip](https://github.com/onnx/onnx-tensorflow/files/7731927/model_onnx.onnx.zip)

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: python3.9
 - ONNX version: 1.10.2
 - ONNX-TF version:1.9.0
 - Tensorflow version: 2.7.0

**Additional context**

**Comment by shichaog** [comment]
I change file conv_mixin.py   and add BOLD segement.
Because in my case group==4 still can't use depthwise convolution to implement
# Is this convolution depthwise we can support?
    depthwise = (x_rank == 4 and len(weight_shape) == 4 and group != 1 **and group != 4** and
                 not transpose and not (None in weight_shape))

**Comment by shichaog** [comment]
and group != 4 is just for my case skip depthwise, So the solution should comapre input channels with output chanels and groups?

**Comment by Daveorr** [comment]
Hi, I'm facing the same issue. 

- Can convert to pytorch to Onnx
- Can run inference using ONNX runtime
- Can generate Tensorflow Representation as `tf_rep = prepare(onnx_model)`

FAILS when calling `tf_rep.export_graph(out.pb')` with:

`ValueError: Dimensions must be equal, but are 3072 and 96 for '{{node Add_1263}} = AddV2[T=DT_FLOAT](concat_19/concat, Add_1263/y)' with input shapes: [?,?,?,3072], [96].`

Did someone managed to solve this issue???

**Comment by dani3l125** [comment]
Hello @Daveorr, did you eventually find a solution?
